// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: store.proto

package com.grpc.store;

/**
 * Protobuf type {@code com.grpc.store.Aisle}
 */
public final class Aisle extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.grpc.store.Aisle)
    AisleOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Aisle.newBuilder() to construct.
  private Aisle(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Aisle() {
    bays_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Aisle();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Aisle(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            com.grpc.store.UUID.Builder subBuilder = null;
            if (id_ != null) {
              subBuilder = id_.toBuilder();
            }
            id_ = input.readMessage(com.grpc.store.UUID.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(id_);
              id_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            com.grpc.store.Coordinate.Builder subBuilder = null;
            if (location_ != null) {
              subBuilder = location_.toBuilder();
            }
            location_ = input.readMessage(com.grpc.store.Coordinate.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(location_);
              location_ = subBuilder.buildPartial();
            }

            break;
          }
          case 26: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              bays_ = new java.util.ArrayList<com.grpc.store.Bay>();
              mutable_bitField0_ |= 0x00000001;
            }
            bays_.add(
                input.readMessage(com.grpc.store.Bay.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        bays_ = java.util.Collections.unmodifiableList(bays_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.grpc.store.StoreCover.internal_static_com_grpc_store_Aisle_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.grpc.store.StoreCover.internal_static_com_grpc_store_Aisle_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.grpc.store.Aisle.class, com.grpc.store.Aisle.Builder.class);
  }

  public static final int ID_FIELD_NUMBER = 1;
  private com.grpc.store.UUID id_;
  /**
   * <code>.com.grpc.store.UUID id = 1;</code>
   * @return Whether the id field is set.
   */
  @java.lang.Override
  public boolean hasId() {
    return id_ != null;
  }
  /**
   * <code>.com.grpc.store.UUID id = 1;</code>
   * @return The id.
   */
  @java.lang.Override
  public com.grpc.store.UUID getId() {
    return id_ == null ? com.grpc.store.UUID.getDefaultInstance() : id_;
  }
  /**
   * <code>.com.grpc.store.UUID id = 1;</code>
   */
  @java.lang.Override
  public com.grpc.store.UUIDOrBuilder getIdOrBuilder() {
    return getId();
  }

  public static final int LOCATION_FIELD_NUMBER = 2;
  private com.grpc.store.Coordinate location_;
  /**
   * <code>.com.grpc.store.Coordinate location = 2;</code>
   * @return Whether the location field is set.
   */
  @java.lang.Override
  public boolean hasLocation() {
    return location_ != null;
  }
  /**
   * <code>.com.grpc.store.Coordinate location = 2;</code>
   * @return The location.
   */
  @java.lang.Override
  public com.grpc.store.Coordinate getLocation() {
    return location_ == null ? com.grpc.store.Coordinate.getDefaultInstance() : location_;
  }
  /**
   * <code>.com.grpc.store.Coordinate location = 2;</code>
   */
  @java.lang.Override
  public com.grpc.store.CoordinateOrBuilder getLocationOrBuilder() {
    return getLocation();
  }

  public static final int BAYS_FIELD_NUMBER = 3;
  private java.util.List<com.grpc.store.Bay> bays_;
  /**
   * <code>repeated .com.grpc.store.Bay bays = 3;</code>
   */
  @java.lang.Override
  public java.util.List<com.grpc.store.Bay> getBaysList() {
    return bays_;
  }
  /**
   * <code>repeated .com.grpc.store.Bay bays = 3;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.grpc.store.BayOrBuilder> 
      getBaysOrBuilderList() {
    return bays_;
  }
  /**
   * <code>repeated .com.grpc.store.Bay bays = 3;</code>
   */
  @java.lang.Override
  public int getBaysCount() {
    return bays_.size();
  }
  /**
   * <code>repeated .com.grpc.store.Bay bays = 3;</code>
   */
  @java.lang.Override
  public com.grpc.store.Bay getBays(int index) {
    return bays_.get(index);
  }
  /**
   * <code>repeated .com.grpc.store.Bay bays = 3;</code>
   */
  @java.lang.Override
  public com.grpc.store.BayOrBuilder getBaysOrBuilder(
      int index) {
    return bays_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (id_ != null) {
      output.writeMessage(1, getId());
    }
    if (location_ != null) {
      output.writeMessage(2, getLocation());
    }
    for (int i = 0; i < bays_.size(); i++) {
      output.writeMessage(3, bays_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (id_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getId());
    }
    if (location_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getLocation());
    }
    for (int i = 0; i < bays_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, bays_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.grpc.store.Aisle)) {
      return super.equals(obj);
    }
    com.grpc.store.Aisle other = (com.grpc.store.Aisle) obj;

    if (hasId() != other.hasId()) return false;
    if (hasId()) {
      if (!getId()
          .equals(other.getId())) return false;
    }
    if (hasLocation() != other.hasLocation()) return false;
    if (hasLocation()) {
      if (!getLocation()
          .equals(other.getLocation())) return false;
    }
    if (!getBaysList()
        .equals(other.getBaysList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasId()) {
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId().hashCode();
    }
    if (hasLocation()) {
      hash = (37 * hash) + LOCATION_FIELD_NUMBER;
      hash = (53 * hash) + getLocation().hashCode();
    }
    if (getBaysCount() > 0) {
      hash = (37 * hash) + BAYS_FIELD_NUMBER;
      hash = (53 * hash) + getBaysList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.grpc.store.Aisle parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.grpc.store.Aisle parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.grpc.store.Aisle parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.grpc.store.Aisle parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.grpc.store.Aisle parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.grpc.store.Aisle parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.grpc.store.Aisle parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.grpc.store.Aisle parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.grpc.store.Aisle parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.grpc.store.Aisle parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.grpc.store.Aisle parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.grpc.store.Aisle parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.grpc.store.Aisle prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.grpc.store.Aisle}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.grpc.store.Aisle)
      com.grpc.store.AisleOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.grpc.store.StoreCover.internal_static_com_grpc_store_Aisle_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.grpc.store.StoreCover.internal_static_com_grpc_store_Aisle_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.grpc.store.Aisle.class, com.grpc.store.Aisle.Builder.class);
    }

    // Construct using com.grpc.store.Aisle.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getBaysFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (idBuilder_ == null) {
        id_ = null;
      } else {
        id_ = null;
        idBuilder_ = null;
      }
      if (locationBuilder_ == null) {
        location_ = null;
      } else {
        location_ = null;
        locationBuilder_ = null;
      }
      if (baysBuilder_ == null) {
        bays_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        baysBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.grpc.store.StoreCover.internal_static_com_grpc_store_Aisle_descriptor;
    }

    @java.lang.Override
    public com.grpc.store.Aisle getDefaultInstanceForType() {
      return com.grpc.store.Aisle.getDefaultInstance();
    }

    @java.lang.Override
    public com.grpc.store.Aisle build() {
      com.grpc.store.Aisle result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.grpc.store.Aisle buildPartial() {
      com.grpc.store.Aisle result = new com.grpc.store.Aisle(this);
      int from_bitField0_ = bitField0_;
      if (idBuilder_ == null) {
        result.id_ = id_;
      } else {
        result.id_ = idBuilder_.build();
      }
      if (locationBuilder_ == null) {
        result.location_ = location_;
      } else {
        result.location_ = locationBuilder_.build();
      }
      if (baysBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          bays_ = java.util.Collections.unmodifiableList(bays_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.bays_ = bays_;
      } else {
        result.bays_ = baysBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.grpc.store.Aisle) {
        return mergeFrom((com.grpc.store.Aisle)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.grpc.store.Aisle other) {
      if (other == com.grpc.store.Aisle.getDefaultInstance()) return this;
      if (other.hasId()) {
        mergeId(other.getId());
      }
      if (other.hasLocation()) {
        mergeLocation(other.getLocation());
      }
      if (baysBuilder_ == null) {
        if (!other.bays_.isEmpty()) {
          if (bays_.isEmpty()) {
            bays_ = other.bays_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureBaysIsMutable();
            bays_.addAll(other.bays_);
          }
          onChanged();
        }
      } else {
        if (!other.bays_.isEmpty()) {
          if (baysBuilder_.isEmpty()) {
            baysBuilder_.dispose();
            baysBuilder_ = null;
            bays_ = other.bays_;
            bitField0_ = (bitField0_ & ~0x00000001);
            baysBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getBaysFieldBuilder() : null;
          } else {
            baysBuilder_.addAllMessages(other.bays_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.grpc.store.Aisle parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.grpc.store.Aisle) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private com.grpc.store.UUID id_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.grpc.store.UUID, com.grpc.store.UUID.Builder, com.grpc.store.UUIDOrBuilder> idBuilder_;
    /**
     * <code>.com.grpc.store.UUID id = 1;</code>
     * @return Whether the id field is set.
     */
    public boolean hasId() {
      return idBuilder_ != null || id_ != null;
    }
    /**
     * <code>.com.grpc.store.UUID id = 1;</code>
     * @return The id.
     */
    public com.grpc.store.UUID getId() {
      if (idBuilder_ == null) {
        return id_ == null ? com.grpc.store.UUID.getDefaultInstance() : id_;
      } else {
        return idBuilder_.getMessage();
      }
    }
    /**
     * <code>.com.grpc.store.UUID id = 1;</code>
     */
    public Builder setId(com.grpc.store.UUID value) {
      if (idBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        id_ = value;
        onChanged();
      } else {
        idBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.com.grpc.store.UUID id = 1;</code>
     */
    public Builder setId(
        com.grpc.store.UUID.Builder builderForValue) {
      if (idBuilder_ == null) {
        id_ = builderForValue.build();
        onChanged();
      } else {
        idBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.com.grpc.store.UUID id = 1;</code>
     */
    public Builder mergeId(com.grpc.store.UUID value) {
      if (idBuilder_ == null) {
        if (id_ != null) {
          id_ =
            com.grpc.store.UUID.newBuilder(id_).mergeFrom(value).buildPartial();
        } else {
          id_ = value;
        }
        onChanged();
      } else {
        idBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.com.grpc.store.UUID id = 1;</code>
     */
    public Builder clearId() {
      if (idBuilder_ == null) {
        id_ = null;
        onChanged();
      } else {
        id_ = null;
        idBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.com.grpc.store.UUID id = 1;</code>
     */
    public com.grpc.store.UUID.Builder getIdBuilder() {
      
      onChanged();
      return getIdFieldBuilder().getBuilder();
    }
    /**
     * <code>.com.grpc.store.UUID id = 1;</code>
     */
    public com.grpc.store.UUIDOrBuilder getIdOrBuilder() {
      if (idBuilder_ != null) {
        return idBuilder_.getMessageOrBuilder();
      } else {
        return id_ == null ?
            com.grpc.store.UUID.getDefaultInstance() : id_;
      }
    }
    /**
     * <code>.com.grpc.store.UUID id = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.grpc.store.UUID, com.grpc.store.UUID.Builder, com.grpc.store.UUIDOrBuilder> 
        getIdFieldBuilder() {
      if (idBuilder_ == null) {
        idBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.grpc.store.UUID, com.grpc.store.UUID.Builder, com.grpc.store.UUIDOrBuilder>(
                getId(),
                getParentForChildren(),
                isClean());
        id_ = null;
      }
      return idBuilder_;
    }

    private com.grpc.store.Coordinate location_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.grpc.store.Coordinate, com.grpc.store.Coordinate.Builder, com.grpc.store.CoordinateOrBuilder> locationBuilder_;
    /**
     * <code>.com.grpc.store.Coordinate location = 2;</code>
     * @return Whether the location field is set.
     */
    public boolean hasLocation() {
      return locationBuilder_ != null || location_ != null;
    }
    /**
     * <code>.com.grpc.store.Coordinate location = 2;</code>
     * @return The location.
     */
    public com.grpc.store.Coordinate getLocation() {
      if (locationBuilder_ == null) {
        return location_ == null ? com.grpc.store.Coordinate.getDefaultInstance() : location_;
      } else {
        return locationBuilder_.getMessage();
      }
    }
    /**
     * <code>.com.grpc.store.Coordinate location = 2;</code>
     */
    public Builder setLocation(com.grpc.store.Coordinate value) {
      if (locationBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        location_ = value;
        onChanged();
      } else {
        locationBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.com.grpc.store.Coordinate location = 2;</code>
     */
    public Builder setLocation(
        com.grpc.store.Coordinate.Builder builderForValue) {
      if (locationBuilder_ == null) {
        location_ = builderForValue.build();
        onChanged();
      } else {
        locationBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.com.grpc.store.Coordinate location = 2;</code>
     */
    public Builder mergeLocation(com.grpc.store.Coordinate value) {
      if (locationBuilder_ == null) {
        if (location_ != null) {
          location_ =
            com.grpc.store.Coordinate.newBuilder(location_).mergeFrom(value).buildPartial();
        } else {
          location_ = value;
        }
        onChanged();
      } else {
        locationBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.com.grpc.store.Coordinate location = 2;</code>
     */
    public Builder clearLocation() {
      if (locationBuilder_ == null) {
        location_ = null;
        onChanged();
      } else {
        location_ = null;
        locationBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.com.grpc.store.Coordinate location = 2;</code>
     */
    public com.grpc.store.Coordinate.Builder getLocationBuilder() {
      
      onChanged();
      return getLocationFieldBuilder().getBuilder();
    }
    /**
     * <code>.com.grpc.store.Coordinate location = 2;</code>
     */
    public com.grpc.store.CoordinateOrBuilder getLocationOrBuilder() {
      if (locationBuilder_ != null) {
        return locationBuilder_.getMessageOrBuilder();
      } else {
        return location_ == null ?
            com.grpc.store.Coordinate.getDefaultInstance() : location_;
      }
    }
    /**
     * <code>.com.grpc.store.Coordinate location = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.grpc.store.Coordinate, com.grpc.store.Coordinate.Builder, com.grpc.store.CoordinateOrBuilder> 
        getLocationFieldBuilder() {
      if (locationBuilder_ == null) {
        locationBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.grpc.store.Coordinate, com.grpc.store.Coordinate.Builder, com.grpc.store.CoordinateOrBuilder>(
                getLocation(),
                getParentForChildren(),
                isClean());
        location_ = null;
      }
      return locationBuilder_;
    }

    private java.util.List<com.grpc.store.Bay> bays_ =
      java.util.Collections.emptyList();
    private void ensureBaysIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        bays_ = new java.util.ArrayList<com.grpc.store.Bay>(bays_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.grpc.store.Bay, com.grpc.store.Bay.Builder, com.grpc.store.BayOrBuilder> baysBuilder_;

    /**
     * <code>repeated .com.grpc.store.Bay bays = 3;</code>
     */
    public java.util.List<com.grpc.store.Bay> getBaysList() {
      if (baysBuilder_ == null) {
        return java.util.Collections.unmodifiableList(bays_);
      } else {
        return baysBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .com.grpc.store.Bay bays = 3;</code>
     */
    public int getBaysCount() {
      if (baysBuilder_ == null) {
        return bays_.size();
      } else {
        return baysBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .com.grpc.store.Bay bays = 3;</code>
     */
    public com.grpc.store.Bay getBays(int index) {
      if (baysBuilder_ == null) {
        return bays_.get(index);
      } else {
        return baysBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .com.grpc.store.Bay bays = 3;</code>
     */
    public Builder setBays(
        int index, com.grpc.store.Bay value) {
      if (baysBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureBaysIsMutable();
        bays_.set(index, value);
        onChanged();
      } else {
        baysBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.grpc.store.Bay bays = 3;</code>
     */
    public Builder setBays(
        int index, com.grpc.store.Bay.Builder builderForValue) {
      if (baysBuilder_ == null) {
        ensureBaysIsMutable();
        bays_.set(index, builderForValue.build());
        onChanged();
      } else {
        baysBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.grpc.store.Bay bays = 3;</code>
     */
    public Builder addBays(com.grpc.store.Bay value) {
      if (baysBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureBaysIsMutable();
        bays_.add(value);
        onChanged();
      } else {
        baysBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .com.grpc.store.Bay bays = 3;</code>
     */
    public Builder addBays(
        int index, com.grpc.store.Bay value) {
      if (baysBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureBaysIsMutable();
        bays_.add(index, value);
        onChanged();
      } else {
        baysBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.grpc.store.Bay bays = 3;</code>
     */
    public Builder addBays(
        com.grpc.store.Bay.Builder builderForValue) {
      if (baysBuilder_ == null) {
        ensureBaysIsMutable();
        bays_.add(builderForValue.build());
        onChanged();
      } else {
        baysBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.grpc.store.Bay bays = 3;</code>
     */
    public Builder addBays(
        int index, com.grpc.store.Bay.Builder builderForValue) {
      if (baysBuilder_ == null) {
        ensureBaysIsMutable();
        bays_.add(index, builderForValue.build());
        onChanged();
      } else {
        baysBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.grpc.store.Bay bays = 3;</code>
     */
    public Builder addAllBays(
        java.lang.Iterable<? extends com.grpc.store.Bay> values) {
      if (baysBuilder_ == null) {
        ensureBaysIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, bays_);
        onChanged();
      } else {
        baysBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .com.grpc.store.Bay bays = 3;</code>
     */
    public Builder clearBays() {
      if (baysBuilder_ == null) {
        bays_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        baysBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .com.grpc.store.Bay bays = 3;</code>
     */
    public Builder removeBays(int index) {
      if (baysBuilder_ == null) {
        ensureBaysIsMutable();
        bays_.remove(index);
        onChanged();
      } else {
        baysBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .com.grpc.store.Bay bays = 3;</code>
     */
    public com.grpc.store.Bay.Builder getBaysBuilder(
        int index) {
      return getBaysFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .com.grpc.store.Bay bays = 3;</code>
     */
    public com.grpc.store.BayOrBuilder getBaysOrBuilder(
        int index) {
      if (baysBuilder_ == null) {
        return bays_.get(index);  } else {
        return baysBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .com.grpc.store.Bay bays = 3;</code>
     */
    public java.util.List<? extends com.grpc.store.BayOrBuilder> 
         getBaysOrBuilderList() {
      if (baysBuilder_ != null) {
        return baysBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(bays_);
      }
    }
    /**
     * <code>repeated .com.grpc.store.Bay bays = 3;</code>
     */
    public com.grpc.store.Bay.Builder addBaysBuilder() {
      return getBaysFieldBuilder().addBuilder(
          com.grpc.store.Bay.getDefaultInstance());
    }
    /**
     * <code>repeated .com.grpc.store.Bay bays = 3;</code>
     */
    public com.grpc.store.Bay.Builder addBaysBuilder(
        int index) {
      return getBaysFieldBuilder().addBuilder(
          index, com.grpc.store.Bay.getDefaultInstance());
    }
    /**
     * <code>repeated .com.grpc.store.Bay bays = 3;</code>
     */
    public java.util.List<com.grpc.store.Bay.Builder> 
         getBaysBuilderList() {
      return getBaysFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.grpc.store.Bay, com.grpc.store.Bay.Builder, com.grpc.store.BayOrBuilder> 
        getBaysFieldBuilder() {
      if (baysBuilder_ == null) {
        baysBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.grpc.store.Bay, com.grpc.store.Bay.Builder, com.grpc.store.BayOrBuilder>(
                bays_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        bays_ = null;
      }
      return baysBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.grpc.store.Aisle)
  }

  // @@protoc_insertion_point(class_scope:com.grpc.store.Aisle)
  private static final com.grpc.store.Aisle DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.grpc.store.Aisle();
  }

  public static com.grpc.store.Aisle getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Aisle>
      PARSER = new com.google.protobuf.AbstractParser<Aisle>() {
    @java.lang.Override
    public Aisle parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Aisle(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Aisle> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Aisle> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.grpc.store.Aisle getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

