// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: store.proto

package com.grpc.store;

public interface BayOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.grpc.store.Bay)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.com.grpc.store.UUID id = 1;</code>
   * @return Whether the id field is set.
   */
  boolean hasId();
  /**
   * <code>.com.grpc.store.UUID id = 1;</code>
   * @return The id.
   */
  com.grpc.store.UUID getId();
  /**
   * <code>.com.grpc.store.UUID id = 1;</code>
   */
  com.grpc.store.UUIDOrBuilder getIdOrBuilder();

  /**
   * <code>int32 count = 2;</code>
   * @return The count.
   */
  int getCount();

  /**
   * <code>.com.grpc.store.Dimension dimension = 3;</code>
   * @return Whether the dimension field is set.
   */
  boolean hasDimension();
  /**
   * <code>.com.grpc.store.Dimension dimension = 3;</code>
   * @return The dimension.
   */
  com.grpc.store.Dimension getDimension();
  /**
   * <code>.com.grpc.store.Dimension dimension = 3;</code>
   */
  com.grpc.store.DimensionOrBuilder getDimensionOrBuilder();
}
