// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: store.proto

package com.grpc.store;

public interface CoordinateOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.grpc.store.Coordinate)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>float lat = 1;</code>
   * @return The lat.
   */
  float getLat();

  /**
   * <code>float log = 2;</code>
   * @return The log.
   */
  float getLog();

  /**
   * <code>float alt = 3;</code>
   * @return The alt.
   */
  float getAlt();
}
