// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: store.proto

package com.grpc.store;

/**
 * Protobuf type {@code com.grpc.store.Coordinate}
 */
public final class Coordinate extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.grpc.store.Coordinate)
    CoordinateOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Coordinate.newBuilder() to construct.
  private Coordinate(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Coordinate() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Coordinate();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Coordinate(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 13: {

            lat_ = input.readFloat();
            break;
          }
          case 21: {

            log_ = input.readFloat();
            break;
          }
          case 29: {

            alt_ = input.readFloat();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.grpc.store.StoreCover.internal_static_com_grpc_store_Coordinate_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.grpc.store.StoreCover.internal_static_com_grpc_store_Coordinate_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.grpc.store.Coordinate.class, com.grpc.store.Coordinate.Builder.class);
  }

  public static final int LAT_FIELD_NUMBER = 1;
  private float lat_;
  /**
   * <code>float lat = 1;</code>
   * @return The lat.
   */
  @java.lang.Override
  public float getLat() {
    return lat_;
  }

  public static final int LOG_FIELD_NUMBER = 2;
  private float log_;
  /**
   * <code>float log = 2;</code>
   * @return The log.
   */
  @java.lang.Override
  public float getLog() {
    return log_;
  }

  public static final int ALT_FIELD_NUMBER = 3;
  private float alt_;
  /**
   * <code>float alt = 3;</code>
   * @return The alt.
   */
  @java.lang.Override
  public float getAlt() {
    return alt_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (lat_ != 0F) {
      output.writeFloat(1, lat_);
    }
    if (log_ != 0F) {
      output.writeFloat(2, log_);
    }
    if (alt_ != 0F) {
      output.writeFloat(3, alt_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (lat_ != 0F) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(1, lat_);
    }
    if (log_ != 0F) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(2, log_);
    }
    if (alt_ != 0F) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(3, alt_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.grpc.store.Coordinate)) {
      return super.equals(obj);
    }
    com.grpc.store.Coordinate other = (com.grpc.store.Coordinate) obj;

    if (java.lang.Float.floatToIntBits(getLat())
        != java.lang.Float.floatToIntBits(
            other.getLat())) return false;
    if (java.lang.Float.floatToIntBits(getLog())
        != java.lang.Float.floatToIntBits(
            other.getLog())) return false;
    if (java.lang.Float.floatToIntBits(getAlt())
        != java.lang.Float.floatToIntBits(
            other.getAlt())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + LAT_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getLat());
    hash = (37 * hash) + LOG_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getLog());
    hash = (37 * hash) + ALT_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getAlt());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.grpc.store.Coordinate parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.grpc.store.Coordinate parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.grpc.store.Coordinate parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.grpc.store.Coordinate parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.grpc.store.Coordinate parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.grpc.store.Coordinate parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.grpc.store.Coordinate parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.grpc.store.Coordinate parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.grpc.store.Coordinate parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.grpc.store.Coordinate parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.grpc.store.Coordinate parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.grpc.store.Coordinate parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.grpc.store.Coordinate prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.grpc.store.Coordinate}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.grpc.store.Coordinate)
      com.grpc.store.CoordinateOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.grpc.store.StoreCover.internal_static_com_grpc_store_Coordinate_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.grpc.store.StoreCover.internal_static_com_grpc_store_Coordinate_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.grpc.store.Coordinate.class, com.grpc.store.Coordinate.Builder.class);
    }

    // Construct using com.grpc.store.Coordinate.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      lat_ = 0F;

      log_ = 0F;

      alt_ = 0F;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.grpc.store.StoreCover.internal_static_com_grpc_store_Coordinate_descriptor;
    }

    @java.lang.Override
    public com.grpc.store.Coordinate getDefaultInstanceForType() {
      return com.grpc.store.Coordinate.getDefaultInstance();
    }

    @java.lang.Override
    public com.grpc.store.Coordinate build() {
      com.grpc.store.Coordinate result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.grpc.store.Coordinate buildPartial() {
      com.grpc.store.Coordinate result = new com.grpc.store.Coordinate(this);
      result.lat_ = lat_;
      result.log_ = log_;
      result.alt_ = alt_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.grpc.store.Coordinate) {
        return mergeFrom((com.grpc.store.Coordinate)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.grpc.store.Coordinate other) {
      if (other == com.grpc.store.Coordinate.getDefaultInstance()) return this;
      if (other.getLat() != 0F) {
        setLat(other.getLat());
      }
      if (other.getLog() != 0F) {
        setLog(other.getLog());
      }
      if (other.getAlt() != 0F) {
        setAlt(other.getAlt());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.grpc.store.Coordinate parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.grpc.store.Coordinate) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private float lat_ ;
    /**
     * <code>float lat = 1;</code>
     * @return The lat.
     */
    @java.lang.Override
    public float getLat() {
      return lat_;
    }
    /**
     * <code>float lat = 1;</code>
     * @param value The lat to set.
     * @return This builder for chaining.
     */
    public Builder setLat(float value) {
      
      lat_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>float lat = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearLat() {
      
      lat_ = 0F;
      onChanged();
      return this;
    }

    private float log_ ;
    /**
     * <code>float log = 2;</code>
     * @return The log.
     */
    @java.lang.Override
    public float getLog() {
      return log_;
    }
    /**
     * <code>float log = 2;</code>
     * @param value The log to set.
     * @return This builder for chaining.
     */
    public Builder setLog(float value) {
      
      log_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>float log = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearLog() {
      
      log_ = 0F;
      onChanged();
      return this;
    }

    private float alt_ ;
    /**
     * <code>float alt = 3;</code>
     * @return The alt.
     */
    @java.lang.Override
    public float getAlt() {
      return alt_;
    }
    /**
     * <code>float alt = 3;</code>
     * @param value The alt to set.
     * @return This builder for chaining.
     */
    public Builder setAlt(float value) {
      
      alt_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>float alt = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearAlt() {
      
      alt_ = 0F;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.grpc.store.Coordinate)
  }

  // @@protoc_insertion_point(class_scope:com.grpc.store.Coordinate)
  private static final com.grpc.store.Coordinate DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.grpc.store.Coordinate();
  }

  public static com.grpc.store.Coordinate getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Coordinate>
      PARSER = new com.google.protobuf.AbstractParser<Coordinate>() {
    @java.lang.Override
    public Coordinate parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Coordinate(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Coordinate> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Coordinate> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.grpc.store.Coordinate getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

