// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: store.proto

package com.grpc.store;

public interface DimensionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.grpc.store.Dimension)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>float width = 1;</code>
   * @return The width.
   */
  float getWidth();

  /**
   * <code>float height = 2;</code>
   * @return The height.
   */
  float getHeight();

  /**
   * <code>float breadth = 3;</code>
   * @return The breadth.
   */
  float getBreadth();
}
