// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: store.proto

package com.grpc.store;

public final class StoreCover {
  private StoreCover() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_grpc_store_Store_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_grpc_store_Store_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_grpc_store_Timing_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_grpc_store_Timing_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_grpc_store_Aisle_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_grpc_store_Aisle_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_grpc_store_Bay_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_grpc_store_Bay_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_grpc_store_Coordinate_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_grpc_store_Coordinate_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_grpc_store_Dimension_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_grpc_store_Dimension_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_grpc_store_UUID_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_grpc_store_UUID_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_grpc_store_StoreCall_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_grpc_store_StoreCall_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013store.proto\022\016com.grpc.store\032\033google/pr" +
      "otobuf/empty.proto\032\037google/protobuf/time" +
      "stamp.proto\"\314\002\n\005Store\022 \n\002id\030\001 \001(\0132\024.com." +
      "grpc.store.UUID\022\017\n\007address\030\002 \001(\t\022\017\n\007cont" +
      "act\030\003 \001(\003\022/\n\013openingDate\030\004 \001(\0132\032.google." +
      "protobuf.Timestamp\022%\n\006aisles\030\005 \003(\0132\025.com" +
      ".grpc.store.Aisle\022,\n\006status\030\006 \001(\0162\034.com." +
      "grpc.store.Store.Status\022&\n\006timing\030\007 \001(\0132" +
      "\026.com.grpc.store.Timing\"Q\n\006Status\022\n\n\006CLO" +
      "SED\020\000\022\n\n\006OPENED\020\001\022\026\n\022PERMANENTLY_CLOSED\020" +
      "\002\022\027\n\023WILL_OPEN_IN_FUTURE\020\003\"a\n\006Timing\022*\n\006" +
      "openAt\030\001 \001(\0132\032.google.protobuf.Timestamp" +
      "\022+\n\007closeAt\030\002 \001(\0132\032.google.protobuf.Time" +
      "stamp\"z\n\005Aisle\022 \n\002id\030\001 \001(\0132\024.com.grpc.st" +
      "ore.UUID\022,\n\010location\030\002 \001(\0132\032.com.grpc.st" +
      "ore.Coordinate\022!\n\004bays\030\003 \003(\0132\023.com.grpc." +
      "store.Bay\"d\n\003Bay\022 \n\002id\030\001 \001(\0132\024.com.grpc." +
      "store.UUID\022\r\n\005count\030\002 \001(\005\022,\n\tdimension\030\003" +
      " \001(\0132\031.com.grpc.store.Dimension\"3\n\nCoord" +
      "inate\022\013\n\003lat\030\001 \001(\002\022\013\n\003log\030\002 \001(\002\022\013\n\003alt\030\003" +
      " \001(\002\";\n\tDimension\022\r\n\005width\030\001 \001(\002\022\016\n\006heig" +
      "ht\030\002 \001(\002\022\017\n\007breadth\030\003 \001(\002\"\024\n\004UUID\022\014\n\004uui" +
      "d\030\001 \001(\t\"\246\002\n\tStoreCall\022 \n\002id\030\001 \001(\0132\024.com." +
      "grpc.store.UUID\022,\n\006status\030\002 \001(\0162\034.com.gr" +
      "pc.store.Store.Status\022 \n\003bay\030\003 \001(\0132\023.com" +
      ".grpc.store.Bay\022$\n\005aisle\030\004 \001(\0132\025.com.grp" +
      "c.store.Aisle\022!\n\004bays\030\005 \001(\0132\023.com.grpc.s" +
      "tore.Bay\022%\n\006aisles\030\006 \001(\0132\025.com.grpc.stor" +
      "e.Aisle\022&\n\006timing\030\007 \001(\0132\026.com.grpc.store" +
      ".Timing\022\017\n\007contact\030\010 \001(\0032\217\003\n\014StoreServic" +
      "e\0229\n\010addStore\022\025.com.grpc.store.Store\032\026.g" +
      "oogle.protobuf.Empty\022E\n\021changeStoreStatu" +
      "s\022\031.com.grpc.store.StoreCall\032\025.com.grpc." +
      "store.Store\022:\n\006addBay\022\031.com.grpc.store.S" +
      "toreCall\032\025.com.grpc.store.Store\022<\n\010addAi" +
      "sle\022\031.com.grpc.store.StoreCall\032\025.com.grp" +
      "c.store.Store\022@\n\014changeTiming\022\031.com.grpc" +
      ".store.StoreCall\032\025.com.grpc.store.Store\022" +
      "A\n\rchangeContact\022\031.com.grpc.store.StoreC" +
      "all\032\025.com.grpc.store.StoreB\036\n\016com.grpc.s" +
      "toreB\nStoreCoverP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.EmptyProto.getDescriptor(),
          com.google.protobuf.TimestampProto.getDescriptor(),
        });
    internal_static_com_grpc_store_Store_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_grpc_store_Store_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_grpc_store_Store_descriptor,
        new java.lang.String[] { "Id", "Address", "Contact", "OpeningDate", "Aisles", "Status", "Timing", });
    internal_static_com_grpc_store_Timing_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_grpc_store_Timing_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_grpc_store_Timing_descriptor,
        new java.lang.String[] { "OpenAt", "CloseAt", });
    internal_static_com_grpc_store_Aisle_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_grpc_store_Aisle_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_grpc_store_Aisle_descriptor,
        new java.lang.String[] { "Id", "Location", "Bays", });
    internal_static_com_grpc_store_Bay_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_grpc_store_Bay_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_grpc_store_Bay_descriptor,
        new java.lang.String[] { "Id", "Count", "Dimension", });
    internal_static_com_grpc_store_Coordinate_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_com_grpc_store_Coordinate_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_grpc_store_Coordinate_descriptor,
        new java.lang.String[] { "Lat", "Log", "Alt", });
    internal_static_com_grpc_store_Dimension_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_com_grpc_store_Dimension_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_grpc_store_Dimension_descriptor,
        new java.lang.String[] { "Width", "Height", "Breadth", });
    internal_static_com_grpc_store_UUID_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_com_grpc_store_UUID_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_grpc_store_UUID_descriptor,
        new java.lang.String[] { "Uuid", });
    internal_static_com_grpc_store_StoreCall_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_com_grpc_store_StoreCall_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_grpc_store_StoreCall_descriptor,
        new java.lang.String[] { "Id", "Status", "Bay", "Aisle", "Bays", "Aisles", "Timing", "Contact", });
    com.google.protobuf.EmptyProto.getDescriptor();
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
