// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: store.proto

package com.grpc.store;

public interface StoreCallOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.grpc.store.StoreCall)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.com.grpc.store.UUID id = 1;</code>
   * @return Whether the id field is set.
   */
  boolean hasId();
  /**
   * <code>.com.grpc.store.UUID id = 1;</code>
   * @return The id.
   */
  com.grpc.store.UUID getId();
  /**
   * <code>.com.grpc.store.UUID id = 1;</code>
   */
  com.grpc.store.UUIDOrBuilder getIdOrBuilder();

  /**
   * <code>.com.grpc.store.Store.Status status = 2;</code>
   * @return The enum numeric value on the wire for status.
   */
  int getStatusValue();
  /**
   * <code>.com.grpc.store.Store.Status status = 2;</code>
   * @return The status.
   */
  com.grpc.store.Store.Status getStatus();

  /**
   * <code>.com.grpc.store.Bay bay = 3;</code>
   * @return Whether the bay field is set.
   */
  boolean hasBay();
  /**
   * <code>.com.grpc.store.Bay bay = 3;</code>
   * @return The bay.
   */
  com.grpc.store.Bay getBay();
  /**
   * <code>.com.grpc.store.Bay bay = 3;</code>
   */
  com.grpc.store.BayOrBuilder getBayOrBuilder();

  /**
   * <code>.com.grpc.store.Aisle aisle = 4;</code>
   * @return Whether the aisle field is set.
   */
  boolean hasAisle();
  /**
   * <code>.com.grpc.store.Aisle aisle = 4;</code>
   * @return The aisle.
   */
  com.grpc.store.Aisle getAisle();
  /**
   * <code>.com.grpc.store.Aisle aisle = 4;</code>
   */
  com.grpc.store.AisleOrBuilder getAisleOrBuilder();

  /**
   * <code>.com.grpc.store.Bay bays = 5;</code>
   * @return Whether the bays field is set.
   */
  boolean hasBays();
  /**
   * <code>.com.grpc.store.Bay bays = 5;</code>
   * @return The bays.
   */
  com.grpc.store.Bay getBays();
  /**
   * <code>.com.grpc.store.Bay bays = 5;</code>
   */
  com.grpc.store.BayOrBuilder getBaysOrBuilder();

  /**
   * <code>.com.grpc.store.Aisle aisles = 6;</code>
   * @return Whether the aisles field is set.
   */
  boolean hasAisles();
  /**
   * <code>.com.grpc.store.Aisle aisles = 6;</code>
   * @return The aisles.
   */
  com.grpc.store.Aisle getAisles();
  /**
   * <code>.com.grpc.store.Aisle aisles = 6;</code>
   */
  com.grpc.store.AisleOrBuilder getAislesOrBuilder();

  /**
   * <code>.com.grpc.store.Timing timing = 7;</code>
   * @return Whether the timing field is set.
   */
  boolean hasTiming();
  /**
   * <code>.com.grpc.store.Timing timing = 7;</code>
   * @return The timing.
   */
  com.grpc.store.Timing getTiming();
  /**
   * <code>.com.grpc.store.Timing timing = 7;</code>
   */
  com.grpc.store.TimingOrBuilder getTimingOrBuilder();

  /**
   * <code>int64 contact = 8;</code>
   * @return The contact.
   */
  long getContact();
}
