// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: store.proto

package com.grpc.store;

public interface StoreOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.grpc.store.Store)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.com.grpc.store.UUID id = 1;</code>
   * @return Whether the id field is set.
   */
  boolean hasId();
  /**
   * <code>.com.grpc.store.UUID id = 1;</code>
   * @return The id.
   */
  com.grpc.store.UUID getId();
  /**
   * <code>.com.grpc.store.UUID id = 1;</code>
   */
  com.grpc.store.UUIDOrBuilder getIdOrBuilder();

  /**
   * <code>string address = 2;</code>
   * @return The address.
   */
  java.lang.String getAddress();
  /**
   * <code>string address = 2;</code>
   * @return The bytes for address.
   */
  com.google.protobuf.ByteString
      getAddressBytes();

  /**
   * <code>int64 contact = 3;</code>
   * @return The contact.
   */
  long getContact();

  /**
   * <code>.google.protobuf.Timestamp openingDate = 4;</code>
   * @return Whether the openingDate field is set.
   */
  boolean hasOpeningDate();
  /**
   * <code>.google.protobuf.Timestamp openingDate = 4;</code>
   * @return The openingDate.
   */
  com.google.protobuf.Timestamp getOpeningDate();
  /**
   * <code>.google.protobuf.Timestamp openingDate = 4;</code>
   */
  com.google.protobuf.TimestampOrBuilder getOpeningDateOrBuilder();

  /**
   * <code>repeated .com.grpc.store.Aisle aisles = 5;</code>
   */
  java.util.List<com.grpc.store.Aisle> 
      getAislesList();
  /**
   * <code>repeated .com.grpc.store.Aisle aisles = 5;</code>
   */
  com.grpc.store.Aisle getAisles(int index);
  /**
   * <code>repeated .com.grpc.store.Aisle aisles = 5;</code>
   */
  int getAislesCount();
  /**
   * <code>repeated .com.grpc.store.Aisle aisles = 5;</code>
   */
  java.util.List<? extends com.grpc.store.AisleOrBuilder> 
      getAislesOrBuilderList();
  /**
   * <code>repeated .com.grpc.store.Aisle aisles = 5;</code>
   */
  com.grpc.store.AisleOrBuilder getAislesOrBuilder(
      int index);

  /**
   * <code>.com.grpc.store.Store.Status status = 6;</code>
   * @return The enum numeric value on the wire for status.
   */
  int getStatusValue();
  /**
   * <code>.com.grpc.store.Store.Status status = 6;</code>
   * @return The status.
   */
  com.grpc.store.Store.Status getStatus();

  /**
   * <code>.com.grpc.store.Timing timing = 7;</code>
   * @return Whether the timing field is set.
   */
  boolean hasTiming();
  /**
   * <code>.com.grpc.store.Timing timing = 7;</code>
   * @return The timing.
   */
  com.grpc.store.Timing getTiming();
  /**
   * <code>.com.grpc.store.Timing timing = 7;</code>
   */
  com.grpc.store.TimingOrBuilder getTimingOrBuilder();
}
