// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: store.proto

package com.grpc.store;

/**
 * Protobuf type {@code com.grpc.store.StoreCall}
 */
public final class StoreCall extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.grpc.store.StoreCall)
    StoreCallOrBuilder {
private static final long serialVersionUID = 0L;
  // Use StoreCall.newBuilder() to construct.
  private StoreCall(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private StoreCall() {
    status_ = 0;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new StoreCall();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private StoreCall(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            com.grpc.store.UUID.Builder subBuilder = null;
            if (id_ != null) {
              subBuilder = id_.toBuilder();
            }
            id_ = input.readMessage(com.grpc.store.UUID.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(id_);
              id_ = subBuilder.buildPartial();
            }

            break;
          }
          case 16: {
            int rawValue = input.readEnum();

            status_ = rawValue;
            break;
          }
          case 26: {
            com.grpc.store.Bay.Builder subBuilder = null;
            if (bay_ != null) {
              subBuilder = bay_.toBuilder();
            }
            bay_ = input.readMessage(com.grpc.store.Bay.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(bay_);
              bay_ = subBuilder.buildPartial();
            }

            break;
          }
          case 34: {
            com.grpc.store.Aisle.Builder subBuilder = null;
            if (aisle_ != null) {
              subBuilder = aisle_.toBuilder();
            }
            aisle_ = input.readMessage(com.grpc.store.Aisle.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(aisle_);
              aisle_ = subBuilder.buildPartial();
            }

            break;
          }
          case 42: {
            com.grpc.store.Bay.Builder subBuilder = null;
            if (bays_ != null) {
              subBuilder = bays_.toBuilder();
            }
            bays_ = input.readMessage(com.grpc.store.Bay.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(bays_);
              bays_ = subBuilder.buildPartial();
            }

            break;
          }
          case 50: {
            com.grpc.store.Aisle.Builder subBuilder = null;
            if (aisles_ != null) {
              subBuilder = aisles_.toBuilder();
            }
            aisles_ = input.readMessage(com.grpc.store.Aisle.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(aisles_);
              aisles_ = subBuilder.buildPartial();
            }

            break;
          }
          case 58: {
            com.grpc.store.Timing.Builder subBuilder = null;
            if (timing_ != null) {
              subBuilder = timing_.toBuilder();
            }
            timing_ = input.readMessage(com.grpc.store.Timing.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(timing_);
              timing_ = subBuilder.buildPartial();
            }

            break;
          }
          case 64: {

            contact_ = input.readInt64();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.grpc.store.StoreCover.internal_static_com_grpc_store_StoreCall_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.grpc.store.StoreCover.internal_static_com_grpc_store_StoreCall_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.grpc.store.StoreCall.class, com.grpc.store.StoreCall.Builder.class);
  }

  public static final int ID_FIELD_NUMBER = 1;
  private com.grpc.store.UUID id_;
  /**
   * <code>.com.grpc.store.UUID id = 1;</code>
   * @return Whether the id field is set.
   */
  @java.lang.Override
  public boolean hasId() {
    return id_ != null;
  }
  /**
   * <code>.com.grpc.store.UUID id = 1;</code>
   * @return The id.
   */
  @java.lang.Override
  public com.grpc.store.UUID getId() {
    return id_ == null ? com.grpc.store.UUID.getDefaultInstance() : id_;
  }
  /**
   * <code>.com.grpc.store.UUID id = 1;</code>
   */
  @java.lang.Override
  public com.grpc.store.UUIDOrBuilder getIdOrBuilder() {
    return getId();
  }

  public static final int STATUS_FIELD_NUMBER = 2;
  private int status_;
  /**
   * <code>.com.grpc.store.Store.Status status = 2;</code>
   * @return The enum numeric value on the wire for status.
   */
  @java.lang.Override public int getStatusValue() {
    return status_;
  }
  /**
   * <code>.com.grpc.store.Store.Status status = 2;</code>
   * @return The status.
   */
  @java.lang.Override public com.grpc.store.Store.Status getStatus() {
    @SuppressWarnings("deprecation")
    com.grpc.store.Store.Status result = com.grpc.store.Store.Status.valueOf(status_);
    return result == null ? com.grpc.store.Store.Status.UNRECOGNIZED : result;
  }

  public static final int BAY_FIELD_NUMBER = 3;
  private com.grpc.store.Bay bay_;
  /**
   * <code>.com.grpc.store.Bay bay = 3;</code>
   * @return Whether the bay field is set.
   */
  @java.lang.Override
  public boolean hasBay() {
    return bay_ != null;
  }
  /**
   * <code>.com.grpc.store.Bay bay = 3;</code>
   * @return The bay.
   */
  @java.lang.Override
  public com.grpc.store.Bay getBay() {
    return bay_ == null ? com.grpc.store.Bay.getDefaultInstance() : bay_;
  }
  /**
   * <code>.com.grpc.store.Bay bay = 3;</code>
   */
  @java.lang.Override
  public com.grpc.store.BayOrBuilder getBayOrBuilder() {
    return getBay();
  }

  public static final int AISLE_FIELD_NUMBER = 4;
  private com.grpc.store.Aisle aisle_;
  /**
   * <code>.com.grpc.store.Aisle aisle = 4;</code>
   * @return Whether the aisle field is set.
   */
  @java.lang.Override
  public boolean hasAisle() {
    return aisle_ != null;
  }
  /**
   * <code>.com.grpc.store.Aisle aisle = 4;</code>
   * @return The aisle.
   */
  @java.lang.Override
  public com.grpc.store.Aisle getAisle() {
    return aisle_ == null ? com.grpc.store.Aisle.getDefaultInstance() : aisle_;
  }
  /**
   * <code>.com.grpc.store.Aisle aisle = 4;</code>
   */
  @java.lang.Override
  public com.grpc.store.AisleOrBuilder getAisleOrBuilder() {
    return getAisle();
  }

  public static final int BAYS_FIELD_NUMBER = 5;
  private com.grpc.store.Bay bays_;
  /**
   * <code>.com.grpc.store.Bay bays = 5;</code>
   * @return Whether the bays field is set.
   */
  @java.lang.Override
  public boolean hasBays() {
    return bays_ != null;
  }
  /**
   * <code>.com.grpc.store.Bay bays = 5;</code>
   * @return The bays.
   */
  @java.lang.Override
  public com.grpc.store.Bay getBays() {
    return bays_ == null ? com.grpc.store.Bay.getDefaultInstance() : bays_;
  }
  /**
   * <code>.com.grpc.store.Bay bays = 5;</code>
   */
  @java.lang.Override
  public com.grpc.store.BayOrBuilder getBaysOrBuilder() {
    return getBays();
  }

  public static final int AISLES_FIELD_NUMBER = 6;
  private com.grpc.store.Aisle aisles_;
  /**
   * <code>.com.grpc.store.Aisle aisles = 6;</code>
   * @return Whether the aisles field is set.
   */
  @java.lang.Override
  public boolean hasAisles() {
    return aisles_ != null;
  }
  /**
   * <code>.com.grpc.store.Aisle aisles = 6;</code>
   * @return The aisles.
   */
  @java.lang.Override
  public com.grpc.store.Aisle getAisles() {
    return aisles_ == null ? com.grpc.store.Aisle.getDefaultInstance() : aisles_;
  }
  /**
   * <code>.com.grpc.store.Aisle aisles = 6;</code>
   */
  @java.lang.Override
  public com.grpc.store.AisleOrBuilder getAislesOrBuilder() {
    return getAisles();
  }

  public static final int TIMING_FIELD_NUMBER = 7;
  private com.grpc.store.Timing timing_;
  /**
   * <code>.com.grpc.store.Timing timing = 7;</code>
   * @return Whether the timing field is set.
   */
  @java.lang.Override
  public boolean hasTiming() {
    return timing_ != null;
  }
  /**
   * <code>.com.grpc.store.Timing timing = 7;</code>
   * @return The timing.
   */
  @java.lang.Override
  public com.grpc.store.Timing getTiming() {
    return timing_ == null ? com.grpc.store.Timing.getDefaultInstance() : timing_;
  }
  /**
   * <code>.com.grpc.store.Timing timing = 7;</code>
   */
  @java.lang.Override
  public com.grpc.store.TimingOrBuilder getTimingOrBuilder() {
    return getTiming();
  }

  public static final int CONTACT_FIELD_NUMBER = 8;
  private long contact_;
  /**
   * <code>int64 contact = 8;</code>
   * @return The contact.
   */
  @java.lang.Override
  public long getContact() {
    return contact_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (id_ != null) {
      output.writeMessage(1, getId());
    }
    if (status_ != com.grpc.store.Store.Status.CLOSED.getNumber()) {
      output.writeEnum(2, status_);
    }
    if (bay_ != null) {
      output.writeMessage(3, getBay());
    }
    if (aisle_ != null) {
      output.writeMessage(4, getAisle());
    }
    if (bays_ != null) {
      output.writeMessage(5, getBays());
    }
    if (aisles_ != null) {
      output.writeMessage(6, getAisles());
    }
    if (timing_ != null) {
      output.writeMessage(7, getTiming());
    }
    if (contact_ != 0L) {
      output.writeInt64(8, contact_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (id_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getId());
    }
    if (status_ != com.grpc.store.Store.Status.CLOSED.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(2, status_);
    }
    if (bay_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getBay());
    }
    if (aisle_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getAisle());
    }
    if (bays_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, getBays());
    }
    if (aisles_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, getAisles());
    }
    if (timing_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(7, getTiming());
    }
    if (contact_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(8, contact_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.grpc.store.StoreCall)) {
      return super.equals(obj);
    }
    com.grpc.store.StoreCall other = (com.grpc.store.StoreCall) obj;

    if (hasId() != other.hasId()) return false;
    if (hasId()) {
      if (!getId()
          .equals(other.getId())) return false;
    }
    if (status_ != other.status_) return false;
    if (hasBay() != other.hasBay()) return false;
    if (hasBay()) {
      if (!getBay()
          .equals(other.getBay())) return false;
    }
    if (hasAisle() != other.hasAisle()) return false;
    if (hasAisle()) {
      if (!getAisle()
          .equals(other.getAisle())) return false;
    }
    if (hasBays() != other.hasBays()) return false;
    if (hasBays()) {
      if (!getBays()
          .equals(other.getBays())) return false;
    }
    if (hasAisles() != other.hasAisles()) return false;
    if (hasAisles()) {
      if (!getAisles()
          .equals(other.getAisles())) return false;
    }
    if (hasTiming() != other.hasTiming()) return false;
    if (hasTiming()) {
      if (!getTiming()
          .equals(other.getTiming())) return false;
    }
    if (getContact()
        != other.getContact()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasId()) {
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId().hashCode();
    }
    hash = (37 * hash) + STATUS_FIELD_NUMBER;
    hash = (53 * hash) + status_;
    if (hasBay()) {
      hash = (37 * hash) + BAY_FIELD_NUMBER;
      hash = (53 * hash) + getBay().hashCode();
    }
    if (hasAisle()) {
      hash = (37 * hash) + AISLE_FIELD_NUMBER;
      hash = (53 * hash) + getAisle().hashCode();
    }
    if (hasBays()) {
      hash = (37 * hash) + BAYS_FIELD_NUMBER;
      hash = (53 * hash) + getBays().hashCode();
    }
    if (hasAisles()) {
      hash = (37 * hash) + AISLES_FIELD_NUMBER;
      hash = (53 * hash) + getAisles().hashCode();
    }
    if (hasTiming()) {
      hash = (37 * hash) + TIMING_FIELD_NUMBER;
      hash = (53 * hash) + getTiming().hashCode();
    }
    hash = (37 * hash) + CONTACT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getContact());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.grpc.store.StoreCall parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.grpc.store.StoreCall parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.grpc.store.StoreCall parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.grpc.store.StoreCall parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.grpc.store.StoreCall parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.grpc.store.StoreCall parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.grpc.store.StoreCall parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.grpc.store.StoreCall parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.grpc.store.StoreCall parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.grpc.store.StoreCall parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.grpc.store.StoreCall parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.grpc.store.StoreCall parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.grpc.store.StoreCall prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.grpc.store.StoreCall}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.grpc.store.StoreCall)
      com.grpc.store.StoreCallOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.grpc.store.StoreCover.internal_static_com_grpc_store_StoreCall_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.grpc.store.StoreCover.internal_static_com_grpc_store_StoreCall_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.grpc.store.StoreCall.class, com.grpc.store.StoreCall.Builder.class);
    }

    // Construct using com.grpc.store.StoreCall.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (idBuilder_ == null) {
        id_ = null;
      } else {
        id_ = null;
        idBuilder_ = null;
      }
      status_ = 0;

      if (bayBuilder_ == null) {
        bay_ = null;
      } else {
        bay_ = null;
        bayBuilder_ = null;
      }
      if (aisleBuilder_ == null) {
        aisle_ = null;
      } else {
        aisle_ = null;
        aisleBuilder_ = null;
      }
      if (baysBuilder_ == null) {
        bays_ = null;
      } else {
        bays_ = null;
        baysBuilder_ = null;
      }
      if (aislesBuilder_ == null) {
        aisles_ = null;
      } else {
        aisles_ = null;
        aislesBuilder_ = null;
      }
      if (timingBuilder_ == null) {
        timing_ = null;
      } else {
        timing_ = null;
        timingBuilder_ = null;
      }
      contact_ = 0L;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.grpc.store.StoreCover.internal_static_com_grpc_store_StoreCall_descriptor;
    }

    @java.lang.Override
    public com.grpc.store.StoreCall getDefaultInstanceForType() {
      return com.grpc.store.StoreCall.getDefaultInstance();
    }

    @java.lang.Override
    public com.grpc.store.StoreCall build() {
      com.grpc.store.StoreCall result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.grpc.store.StoreCall buildPartial() {
      com.grpc.store.StoreCall result = new com.grpc.store.StoreCall(this);
      if (idBuilder_ == null) {
        result.id_ = id_;
      } else {
        result.id_ = idBuilder_.build();
      }
      result.status_ = status_;
      if (bayBuilder_ == null) {
        result.bay_ = bay_;
      } else {
        result.bay_ = bayBuilder_.build();
      }
      if (aisleBuilder_ == null) {
        result.aisle_ = aisle_;
      } else {
        result.aisle_ = aisleBuilder_.build();
      }
      if (baysBuilder_ == null) {
        result.bays_ = bays_;
      } else {
        result.bays_ = baysBuilder_.build();
      }
      if (aislesBuilder_ == null) {
        result.aisles_ = aisles_;
      } else {
        result.aisles_ = aislesBuilder_.build();
      }
      if (timingBuilder_ == null) {
        result.timing_ = timing_;
      } else {
        result.timing_ = timingBuilder_.build();
      }
      result.contact_ = contact_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.grpc.store.StoreCall) {
        return mergeFrom((com.grpc.store.StoreCall)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.grpc.store.StoreCall other) {
      if (other == com.grpc.store.StoreCall.getDefaultInstance()) return this;
      if (other.hasId()) {
        mergeId(other.getId());
      }
      if (other.status_ != 0) {
        setStatusValue(other.getStatusValue());
      }
      if (other.hasBay()) {
        mergeBay(other.getBay());
      }
      if (other.hasAisle()) {
        mergeAisle(other.getAisle());
      }
      if (other.hasBays()) {
        mergeBays(other.getBays());
      }
      if (other.hasAisles()) {
        mergeAisles(other.getAisles());
      }
      if (other.hasTiming()) {
        mergeTiming(other.getTiming());
      }
      if (other.getContact() != 0L) {
        setContact(other.getContact());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.grpc.store.StoreCall parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.grpc.store.StoreCall) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private com.grpc.store.UUID id_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.grpc.store.UUID, com.grpc.store.UUID.Builder, com.grpc.store.UUIDOrBuilder> idBuilder_;
    /**
     * <code>.com.grpc.store.UUID id = 1;</code>
     * @return Whether the id field is set.
     */
    public boolean hasId() {
      return idBuilder_ != null || id_ != null;
    }
    /**
     * <code>.com.grpc.store.UUID id = 1;</code>
     * @return The id.
     */
    public com.grpc.store.UUID getId() {
      if (idBuilder_ == null) {
        return id_ == null ? com.grpc.store.UUID.getDefaultInstance() : id_;
      } else {
        return idBuilder_.getMessage();
      }
    }
    /**
     * <code>.com.grpc.store.UUID id = 1;</code>
     */
    public Builder setId(com.grpc.store.UUID value) {
      if (idBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        id_ = value;
        onChanged();
      } else {
        idBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.com.grpc.store.UUID id = 1;</code>
     */
    public Builder setId(
        com.grpc.store.UUID.Builder builderForValue) {
      if (idBuilder_ == null) {
        id_ = builderForValue.build();
        onChanged();
      } else {
        idBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.com.grpc.store.UUID id = 1;</code>
     */
    public Builder mergeId(com.grpc.store.UUID value) {
      if (idBuilder_ == null) {
        if (id_ != null) {
          id_ =
            com.grpc.store.UUID.newBuilder(id_).mergeFrom(value).buildPartial();
        } else {
          id_ = value;
        }
        onChanged();
      } else {
        idBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.com.grpc.store.UUID id = 1;</code>
     */
    public Builder clearId() {
      if (idBuilder_ == null) {
        id_ = null;
        onChanged();
      } else {
        id_ = null;
        idBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.com.grpc.store.UUID id = 1;</code>
     */
    public com.grpc.store.UUID.Builder getIdBuilder() {
      
      onChanged();
      return getIdFieldBuilder().getBuilder();
    }
    /**
     * <code>.com.grpc.store.UUID id = 1;</code>
     */
    public com.grpc.store.UUIDOrBuilder getIdOrBuilder() {
      if (idBuilder_ != null) {
        return idBuilder_.getMessageOrBuilder();
      } else {
        return id_ == null ?
            com.grpc.store.UUID.getDefaultInstance() : id_;
      }
    }
    /**
     * <code>.com.grpc.store.UUID id = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.grpc.store.UUID, com.grpc.store.UUID.Builder, com.grpc.store.UUIDOrBuilder> 
        getIdFieldBuilder() {
      if (idBuilder_ == null) {
        idBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.grpc.store.UUID, com.grpc.store.UUID.Builder, com.grpc.store.UUIDOrBuilder>(
                getId(),
                getParentForChildren(),
                isClean());
        id_ = null;
      }
      return idBuilder_;
    }

    private int status_ = 0;
    /**
     * <code>.com.grpc.store.Store.Status status = 2;</code>
     * @return The enum numeric value on the wire for status.
     */
    @java.lang.Override public int getStatusValue() {
      return status_;
    }
    /**
     * <code>.com.grpc.store.Store.Status status = 2;</code>
     * @param value The enum numeric value on the wire for status to set.
     * @return This builder for chaining.
     */
    public Builder setStatusValue(int value) {
      
      status_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.com.grpc.store.Store.Status status = 2;</code>
     * @return The status.
     */
    @java.lang.Override
    public com.grpc.store.Store.Status getStatus() {
      @SuppressWarnings("deprecation")
      com.grpc.store.Store.Status result = com.grpc.store.Store.Status.valueOf(status_);
      return result == null ? com.grpc.store.Store.Status.UNRECOGNIZED : result;
    }
    /**
     * <code>.com.grpc.store.Store.Status status = 2;</code>
     * @param value The status to set.
     * @return This builder for chaining.
     */
    public Builder setStatus(com.grpc.store.Store.Status value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      status_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.com.grpc.store.Store.Status status = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearStatus() {
      
      status_ = 0;
      onChanged();
      return this;
    }

    private com.grpc.store.Bay bay_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.grpc.store.Bay, com.grpc.store.Bay.Builder, com.grpc.store.BayOrBuilder> bayBuilder_;
    /**
     * <code>.com.grpc.store.Bay bay = 3;</code>
     * @return Whether the bay field is set.
     */
    public boolean hasBay() {
      return bayBuilder_ != null || bay_ != null;
    }
    /**
     * <code>.com.grpc.store.Bay bay = 3;</code>
     * @return The bay.
     */
    public com.grpc.store.Bay getBay() {
      if (bayBuilder_ == null) {
        return bay_ == null ? com.grpc.store.Bay.getDefaultInstance() : bay_;
      } else {
        return bayBuilder_.getMessage();
      }
    }
    /**
     * <code>.com.grpc.store.Bay bay = 3;</code>
     */
    public Builder setBay(com.grpc.store.Bay value) {
      if (bayBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        bay_ = value;
        onChanged();
      } else {
        bayBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.com.grpc.store.Bay bay = 3;</code>
     */
    public Builder setBay(
        com.grpc.store.Bay.Builder builderForValue) {
      if (bayBuilder_ == null) {
        bay_ = builderForValue.build();
        onChanged();
      } else {
        bayBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.com.grpc.store.Bay bay = 3;</code>
     */
    public Builder mergeBay(com.grpc.store.Bay value) {
      if (bayBuilder_ == null) {
        if (bay_ != null) {
          bay_ =
            com.grpc.store.Bay.newBuilder(bay_).mergeFrom(value).buildPartial();
        } else {
          bay_ = value;
        }
        onChanged();
      } else {
        bayBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.com.grpc.store.Bay bay = 3;</code>
     */
    public Builder clearBay() {
      if (bayBuilder_ == null) {
        bay_ = null;
        onChanged();
      } else {
        bay_ = null;
        bayBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.com.grpc.store.Bay bay = 3;</code>
     */
    public com.grpc.store.Bay.Builder getBayBuilder() {
      
      onChanged();
      return getBayFieldBuilder().getBuilder();
    }
    /**
     * <code>.com.grpc.store.Bay bay = 3;</code>
     */
    public com.grpc.store.BayOrBuilder getBayOrBuilder() {
      if (bayBuilder_ != null) {
        return bayBuilder_.getMessageOrBuilder();
      } else {
        return bay_ == null ?
            com.grpc.store.Bay.getDefaultInstance() : bay_;
      }
    }
    /**
     * <code>.com.grpc.store.Bay bay = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.grpc.store.Bay, com.grpc.store.Bay.Builder, com.grpc.store.BayOrBuilder> 
        getBayFieldBuilder() {
      if (bayBuilder_ == null) {
        bayBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.grpc.store.Bay, com.grpc.store.Bay.Builder, com.grpc.store.BayOrBuilder>(
                getBay(),
                getParentForChildren(),
                isClean());
        bay_ = null;
      }
      return bayBuilder_;
    }

    private com.grpc.store.Aisle aisle_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.grpc.store.Aisle, com.grpc.store.Aisle.Builder, com.grpc.store.AisleOrBuilder> aisleBuilder_;
    /**
     * <code>.com.grpc.store.Aisle aisle = 4;</code>
     * @return Whether the aisle field is set.
     */
    public boolean hasAisle() {
      return aisleBuilder_ != null || aisle_ != null;
    }
    /**
     * <code>.com.grpc.store.Aisle aisle = 4;</code>
     * @return The aisle.
     */
    public com.grpc.store.Aisle getAisle() {
      if (aisleBuilder_ == null) {
        return aisle_ == null ? com.grpc.store.Aisle.getDefaultInstance() : aisle_;
      } else {
        return aisleBuilder_.getMessage();
      }
    }
    /**
     * <code>.com.grpc.store.Aisle aisle = 4;</code>
     */
    public Builder setAisle(com.grpc.store.Aisle value) {
      if (aisleBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        aisle_ = value;
        onChanged();
      } else {
        aisleBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.com.grpc.store.Aisle aisle = 4;</code>
     */
    public Builder setAisle(
        com.grpc.store.Aisle.Builder builderForValue) {
      if (aisleBuilder_ == null) {
        aisle_ = builderForValue.build();
        onChanged();
      } else {
        aisleBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.com.grpc.store.Aisle aisle = 4;</code>
     */
    public Builder mergeAisle(com.grpc.store.Aisle value) {
      if (aisleBuilder_ == null) {
        if (aisle_ != null) {
          aisle_ =
            com.grpc.store.Aisle.newBuilder(aisle_).mergeFrom(value).buildPartial();
        } else {
          aisle_ = value;
        }
        onChanged();
      } else {
        aisleBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.com.grpc.store.Aisle aisle = 4;</code>
     */
    public Builder clearAisle() {
      if (aisleBuilder_ == null) {
        aisle_ = null;
        onChanged();
      } else {
        aisle_ = null;
        aisleBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.com.grpc.store.Aisle aisle = 4;</code>
     */
    public com.grpc.store.Aisle.Builder getAisleBuilder() {
      
      onChanged();
      return getAisleFieldBuilder().getBuilder();
    }
    /**
     * <code>.com.grpc.store.Aisle aisle = 4;</code>
     */
    public com.grpc.store.AisleOrBuilder getAisleOrBuilder() {
      if (aisleBuilder_ != null) {
        return aisleBuilder_.getMessageOrBuilder();
      } else {
        return aisle_ == null ?
            com.grpc.store.Aisle.getDefaultInstance() : aisle_;
      }
    }
    /**
     * <code>.com.grpc.store.Aisle aisle = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.grpc.store.Aisle, com.grpc.store.Aisle.Builder, com.grpc.store.AisleOrBuilder> 
        getAisleFieldBuilder() {
      if (aisleBuilder_ == null) {
        aisleBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.grpc.store.Aisle, com.grpc.store.Aisle.Builder, com.grpc.store.AisleOrBuilder>(
                getAisle(),
                getParentForChildren(),
                isClean());
        aisle_ = null;
      }
      return aisleBuilder_;
    }

    private com.grpc.store.Bay bays_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.grpc.store.Bay, com.grpc.store.Bay.Builder, com.grpc.store.BayOrBuilder> baysBuilder_;
    /**
     * <code>.com.grpc.store.Bay bays = 5;</code>
     * @return Whether the bays field is set.
     */
    public boolean hasBays() {
      return baysBuilder_ != null || bays_ != null;
    }
    /**
     * <code>.com.grpc.store.Bay bays = 5;</code>
     * @return The bays.
     */
    public com.grpc.store.Bay getBays() {
      if (baysBuilder_ == null) {
        return bays_ == null ? com.grpc.store.Bay.getDefaultInstance() : bays_;
      } else {
        return baysBuilder_.getMessage();
      }
    }
    /**
     * <code>.com.grpc.store.Bay bays = 5;</code>
     */
    public Builder setBays(com.grpc.store.Bay value) {
      if (baysBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        bays_ = value;
        onChanged();
      } else {
        baysBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.com.grpc.store.Bay bays = 5;</code>
     */
    public Builder setBays(
        com.grpc.store.Bay.Builder builderForValue) {
      if (baysBuilder_ == null) {
        bays_ = builderForValue.build();
        onChanged();
      } else {
        baysBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.com.grpc.store.Bay bays = 5;</code>
     */
    public Builder mergeBays(com.grpc.store.Bay value) {
      if (baysBuilder_ == null) {
        if (bays_ != null) {
          bays_ =
            com.grpc.store.Bay.newBuilder(bays_).mergeFrom(value).buildPartial();
        } else {
          bays_ = value;
        }
        onChanged();
      } else {
        baysBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.com.grpc.store.Bay bays = 5;</code>
     */
    public Builder clearBays() {
      if (baysBuilder_ == null) {
        bays_ = null;
        onChanged();
      } else {
        bays_ = null;
        baysBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.com.grpc.store.Bay bays = 5;</code>
     */
    public com.grpc.store.Bay.Builder getBaysBuilder() {
      
      onChanged();
      return getBaysFieldBuilder().getBuilder();
    }
    /**
     * <code>.com.grpc.store.Bay bays = 5;</code>
     */
    public com.grpc.store.BayOrBuilder getBaysOrBuilder() {
      if (baysBuilder_ != null) {
        return baysBuilder_.getMessageOrBuilder();
      } else {
        return bays_ == null ?
            com.grpc.store.Bay.getDefaultInstance() : bays_;
      }
    }
    /**
     * <code>.com.grpc.store.Bay bays = 5;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.grpc.store.Bay, com.grpc.store.Bay.Builder, com.grpc.store.BayOrBuilder> 
        getBaysFieldBuilder() {
      if (baysBuilder_ == null) {
        baysBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.grpc.store.Bay, com.grpc.store.Bay.Builder, com.grpc.store.BayOrBuilder>(
                getBays(),
                getParentForChildren(),
                isClean());
        bays_ = null;
      }
      return baysBuilder_;
    }

    private com.grpc.store.Aisle aisles_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.grpc.store.Aisle, com.grpc.store.Aisle.Builder, com.grpc.store.AisleOrBuilder> aislesBuilder_;
    /**
     * <code>.com.grpc.store.Aisle aisles = 6;</code>
     * @return Whether the aisles field is set.
     */
    public boolean hasAisles() {
      return aislesBuilder_ != null || aisles_ != null;
    }
    /**
     * <code>.com.grpc.store.Aisle aisles = 6;</code>
     * @return The aisles.
     */
    public com.grpc.store.Aisle getAisles() {
      if (aislesBuilder_ == null) {
        return aisles_ == null ? com.grpc.store.Aisle.getDefaultInstance() : aisles_;
      } else {
        return aislesBuilder_.getMessage();
      }
    }
    /**
     * <code>.com.grpc.store.Aisle aisles = 6;</code>
     */
    public Builder setAisles(com.grpc.store.Aisle value) {
      if (aislesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        aisles_ = value;
        onChanged();
      } else {
        aislesBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.com.grpc.store.Aisle aisles = 6;</code>
     */
    public Builder setAisles(
        com.grpc.store.Aisle.Builder builderForValue) {
      if (aislesBuilder_ == null) {
        aisles_ = builderForValue.build();
        onChanged();
      } else {
        aislesBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.com.grpc.store.Aisle aisles = 6;</code>
     */
    public Builder mergeAisles(com.grpc.store.Aisle value) {
      if (aislesBuilder_ == null) {
        if (aisles_ != null) {
          aisles_ =
            com.grpc.store.Aisle.newBuilder(aisles_).mergeFrom(value).buildPartial();
        } else {
          aisles_ = value;
        }
        onChanged();
      } else {
        aislesBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.com.grpc.store.Aisle aisles = 6;</code>
     */
    public Builder clearAisles() {
      if (aislesBuilder_ == null) {
        aisles_ = null;
        onChanged();
      } else {
        aisles_ = null;
        aislesBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.com.grpc.store.Aisle aisles = 6;</code>
     */
    public com.grpc.store.Aisle.Builder getAislesBuilder() {
      
      onChanged();
      return getAislesFieldBuilder().getBuilder();
    }
    /**
     * <code>.com.grpc.store.Aisle aisles = 6;</code>
     */
    public com.grpc.store.AisleOrBuilder getAislesOrBuilder() {
      if (aislesBuilder_ != null) {
        return aislesBuilder_.getMessageOrBuilder();
      } else {
        return aisles_ == null ?
            com.grpc.store.Aisle.getDefaultInstance() : aisles_;
      }
    }
    /**
     * <code>.com.grpc.store.Aisle aisles = 6;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.grpc.store.Aisle, com.grpc.store.Aisle.Builder, com.grpc.store.AisleOrBuilder> 
        getAislesFieldBuilder() {
      if (aislesBuilder_ == null) {
        aislesBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.grpc.store.Aisle, com.grpc.store.Aisle.Builder, com.grpc.store.AisleOrBuilder>(
                getAisles(),
                getParentForChildren(),
                isClean());
        aisles_ = null;
      }
      return aislesBuilder_;
    }

    private com.grpc.store.Timing timing_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.grpc.store.Timing, com.grpc.store.Timing.Builder, com.grpc.store.TimingOrBuilder> timingBuilder_;
    /**
     * <code>.com.grpc.store.Timing timing = 7;</code>
     * @return Whether the timing field is set.
     */
    public boolean hasTiming() {
      return timingBuilder_ != null || timing_ != null;
    }
    /**
     * <code>.com.grpc.store.Timing timing = 7;</code>
     * @return The timing.
     */
    public com.grpc.store.Timing getTiming() {
      if (timingBuilder_ == null) {
        return timing_ == null ? com.grpc.store.Timing.getDefaultInstance() : timing_;
      } else {
        return timingBuilder_.getMessage();
      }
    }
    /**
     * <code>.com.grpc.store.Timing timing = 7;</code>
     */
    public Builder setTiming(com.grpc.store.Timing value) {
      if (timingBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        timing_ = value;
        onChanged();
      } else {
        timingBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.com.grpc.store.Timing timing = 7;</code>
     */
    public Builder setTiming(
        com.grpc.store.Timing.Builder builderForValue) {
      if (timingBuilder_ == null) {
        timing_ = builderForValue.build();
        onChanged();
      } else {
        timingBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.com.grpc.store.Timing timing = 7;</code>
     */
    public Builder mergeTiming(com.grpc.store.Timing value) {
      if (timingBuilder_ == null) {
        if (timing_ != null) {
          timing_ =
            com.grpc.store.Timing.newBuilder(timing_).mergeFrom(value).buildPartial();
        } else {
          timing_ = value;
        }
        onChanged();
      } else {
        timingBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.com.grpc.store.Timing timing = 7;</code>
     */
    public Builder clearTiming() {
      if (timingBuilder_ == null) {
        timing_ = null;
        onChanged();
      } else {
        timing_ = null;
        timingBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.com.grpc.store.Timing timing = 7;</code>
     */
    public com.grpc.store.Timing.Builder getTimingBuilder() {
      
      onChanged();
      return getTimingFieldBuilder().getBuilder();
    }
    /**
     * <code>.com.grpc.store.Timing timing = 7;</code>
     */
    public com.grpc.store.TimingOrBuilder getTimingOrBuilder() {
      if (timingBuilder_ != null) {
        return timingBuilder_.getMessageOrBuilder();
      } else {
        return timing_ == null ?
            com.grpc.store.Timing.getDefaultInstance() : timing_;
      }
    }
    /**
     * <code>.com.grpc.store.Timing timing = 7;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.grpc.store.Timing, com.grpc.store.Timing.Builder, com.grpc.store.TimingOrBuilder> 
        getTimingFieldBuilder() {
      if (timingBuilder_ == null) {
        timingBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.grpc.store.Timing, com.grpc.store.Timing.Builder, com.grpc.store.TimingOrBuilder>(
                getTiming(),
                getParentForChildren(),
                isClean());
        timing_ = null;
      }
      return timingBuilder_;
    }

    private long contact_ ;
    /**
     * <code>int64 contact = 8;</code>
     * @return The contact.
     */
    @java.lang.Override
    public long getContact() {
      return contact_;
    }
    /**
     * <code>int64 contact = 8;</code>
     * @param value The contact to set.
     * @return This builder for chaining.
     */
    public Builder setContact(long value) {
      
      contact_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 contact = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearContact() {
      
      contact_ = 0L;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.grpc.store.StoreCall)
  }

  // @@protoc_insertion_point(class_scope:com.grpc.store.StoreCall)
  private static final com.grpc.store.StoreCall DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.grpc.store.StoreCall();
  }

  public static com.grpc.store.StoreCall getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<StoreCall>
      PARSER = new com.google.protobuf.AbstractParser<StoreCall>() {
    @java.lang.Override
    public StoreCall parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new StoreCall(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<StoreCall> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<StoreCall> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.grpc.store.StoreCall getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

