// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: store.proto

package com.grpc.store;

/**
 * Protobuf type {@code com.grpc.store.Store}
 */
public final class Store extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.grpc.store.Store)
    StoreOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Store.newBuilder() to construct.
  private Store(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Store() {
    address_ = "";
    aisles_ = java.util.Collections.emptyList();
    status_ = 0;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Store();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Store(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            com.grpc.store.UUID.Builder subBuilder = null;
            if (id_ != null) {
              subBuilder = id_.toBuilder();
            }
            id_ = input.readMessage(com.grpc.store.UUID.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(id_);
              id_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            address_ = s;
            break;
          }
          case 24: {

            contact_ = input.readInt64();
            break;
          }
          case 34: {
            com.google.protobuf.Timestamp.Builder subBuilder = null;
            if (openingDate_ != null) {
              subBuilder = openingDate_.toBuilder();
            }
            openingDate_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(openingDate_);
              openingDate_ = subBuilder.buildPartial();
            }

            break;
          }
          case 42: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              aisles_ = new java.util.ArrayList<com.grpc.store.Aisle>();
              mutable_bitField0_ |= 0x00000001;
            }
            aisles_.add(
                input.readMessage(com.grpc.store.Aisle.parser(), extensionRegistry));
            break;
          }
          case 48: {
            int rawValue = input.readEnum();

            status_ = rawValue;
            break;
          }
          case 58: {
            com.grpc.store.Timing.Builder subBuilder = null;
            if (timing_ != null) {
              subBuilder = timing_.toBuilder();
            }
            timing_ = input.readMessage(com.grpc.store.Timing.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(timing_);
              timing_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        aisles_ = java.util.Collections.unmodifiableList(aisles_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.grpc.store.StoreCover.internal_static_com_grpc_store_Store_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.grpc.store.StoreCover.internal_static_com_grpc_store_Store_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.grpc.store.Store.class, com.grpc.store.Store.Builder.class);
  }

  /**
   * Protobuf enum {@code com.grpc.store.Store.Status}
   */
  public enum Status
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>CLOSED = 0;</code>
     */
    CLOSED(0),
    /**
     * <code>OPENED = 1;</code>
     */
    OPENED(1),
    /**
     * <code>PERMANENTLY_CLOSED = 2;</code>
     */
    PERMANENTLY_CLOSED(2),
    /**
     * <code>WILL_OPEN_IN_FUTURE = 3;</code>
     */
    WILL_OPEN_IN_FUTURE(3),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>CLOSED = 0;</code>
     */
    public static final int CLOSED_VALUE = 0;
    /**
     * <code>OPENED = 1;</code>
     */
    public static final int OPENED_VALUE = 1;
    /**
     * <code>PERMANENTLY_CLOSED = 2;</code>
     */
    public static final int PERMANENTLY_CLOSED_VALUE = 2;
    /**
     * <code>WILL_OPEN_IN_FUTURE = 3;</code>
     */
    public static final int WILL_OPEN_IN_FUTURE_VALUE = 3;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Status valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static Status forNumber(int value) {
      switch (value) {
        case 0: return CLOSED;
        case 1: return OPENED;
        case 2: return PERMANENTLY_CLOSED;
        case 3: return WILL_OPEN_IN_FUTURE;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Status>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Status> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Status>() {
            public Status findValueByNumber(int number) {
              return Status.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.grpc.store.Store.getDescriptor().getEnumTypes().get(0);
    }

    private static final Status[] VALUES = values();

    public static Status valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Status(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.grpc.store.Store.Status)
  }

  public static final int ID_FIELD_NUMBER = 1;
  private com.grpc.store.UUID id_;
  /**
   * <code>.com.grpc.store.UUID id = 1;</code>
   * @return Whether the id field is set.
   */
  @java.lang.Override
  public boolean hasId() {
    return id_ != null;
  }
  /**
   * <code>.com.grpc.store.UUID id = 1;</code>
   * @return The id.
   */
  @java.lang.Override
  public com.grpc.store.UUID getId() {
    return id_ == null ? com.grpc.store.UUID.getDefaultInstance() : id_;
  }
  /**
   * <code>.com.grpc.store.UUID id = 1;</code>
   */
  @java.lang.Override
  public com.grpc.store.UUIDOrBuilder getIdOrBuilder() {
    return getId();
  }

  public static final int ADDRESS_FIELD_NUMBER = 2;
  private volatile java.lang.Object address_;
  /**
   * <code>string address = 2;</code>
   * @return The address.
   */
  @java.lang.Override
  public java.lang.String getAddress() {
    java.lang.Object ref = address_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      address_ = s;
      return s;
    }
  }
  /**
   * <code>string address = 2;</code>
   * @return The bytes for address.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getAddressBytes() {
    java.lang.Object ref = address_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      address_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CONTACT_FIELD_NUMBER = 3;
  private long contact_;
  /**
   * <code>int64 contact = 3;</code>
   * @return The contact.
   */
  @java.lang.Override
  public long getContact() {
    return contact_;
  }

  public static final int OPENINGDATE_FIELD_NUMBER = 4;
  private com.google.protobuf.Timestamp openingDate_;
  /**
   * <code>.google.protobuf.Timestamp openingDate = 4;</code>
   * @return Whether the openingDate field is set.
   */
  @java.lang.Override
  public boolean hasOpeningDate() {
    return openingDate_ != null;
  }
  /**
   * <code>.google.protobuf.Timestamp openingDate = 4;</code>
   * @return The openingDate.
   */
  @java.lang.Override
  public com.google.protobuf.Timestamp getOpeningDate() {
    return openingDate_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : openingDate_;
  }
  /**
   * <code>.google.protobuf.Timestamp openingDate = 4;</code>
   */
  @java.lang.Override
  public com.google.protobuf.TimestampOrBuilder getOpeningDateOrBuilder() {
    return getOpeningDate();
  }

  public static final int AISLES_FIELD_NUMBER = 5;
  private java.util.List<com.grpc.store.Aisle> aisles_;
  /**
   * <code>repeated .com.grpc.store.Aisle aisles = 5;</code>
   */
  @java.lang.Override
  public java.util.List<com.grpc.store.Aisle> getAislesList() {
    return aisles_;
  }
  /**
   * <code>repeated .com.grpc.store.Aisle aisles = 5;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.grpc.store.AisleOrBuilder> 
      getAislesOrBuilderList() {
    return aisles_;
  }
  /**
   * <code>repeated .com.grpc.store.Aisle aisles = 5;</code>
   */
  @java.lang.Override
  public int getAislesCount() {
    return aisles_.size();
  }
  /**
   * <code>repeated .com.grpc.store.Aisle aisles = 5;</code>
   */
  @java.lang.Override
  public com.grpc.store.Aisle getAisles(int index) {
    return aisles_.get(index);
  }
  /**
   * <code>repeated .com.grpc.store.Aisle aisles = 5;</code>
   */
  @java.lang.Override
  public com.grpc.store.AisleOrBuilder getAislesOrBuilder(
      int index) {
    return aisles_.get(index);
  }

  public static final int STATUS_FIELD_NUMBER = 6;
  private int status_;
  /**
   * <code>.com.grpc.store.Store.Status status = 6;</code>
   * @return The enum numeric value on the wire for status.
   */
  @java.lang.Override public int getStatusValue() {
    return status_;
  }
  /**
   * <code>.com.grpc.store.Store.Status status = 6;</code>
   * @return The status.
   */
  @java.lang.Override public com.grpc.store.Store.Status getStatus() {
    @SuppressWarnings("deprecation")
    com.grpc.store.Store.Status result = com.grpc.store.Store.Status.valueOf(status_);
    return result == null ? com.grpc.store.Store.Status.UNRECOGNIZED : result;
  }

  public static final int TIMING_FIELD_NUMBER = 7;
  private com.grpc.store.Timing timing_;
  /**
   * <code>.com.grpc.store.Timing timing = 7;</code>
   * @return Whether the timing field is set.
   */
  @java.lang.Override
  public boolean hasTiming() {
    return timing_ != null;
  }
  /**
   * <code>.com.grpc.store.Timing timing = 7;</code>
   * @return The timing.
   */
  @java.lang.Override
  public com.grpc.store.Timing getTiming() {
    return timing_ == null ? com.grpc.store.Timing.getDefaultInstance() : timing_;
  }
  /**
   * <code>.com.grpc.store.Timing timing = 7;</code>
   */
  @java.lang.Override
  public com.grpc.store.TimingOrBuilder getTimingOrBuilder() {
    return getTiming();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (id_ != null) {
      output.writeMessage(1, getId());
    }
    if (!getAddressBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, address_);
    }
    if (contact_ != 0L) {
      output.writeInt64(3, contact_);
    }
    if (openingDate_ != null) {
      output.writeMessage(4, getOpeningDate());
    }
    for (int i = 0; i < aisles_.size(); i++) {
      output.writeMessage(5, aisles_.get(i));
    }
    if (status_ != com.grpc.store.Store.Status.CLOSED.getNumber()) {
      output.writeEnum(6, status_);
    }
    if (timing_ != null) {
      output.writeMessage(7, getTiming());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (id_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getId());
    }
    if (!getAddressBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, address_);
    }
    if (contact_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(3, contact_);
    }
    if (openingDate_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getOpeningDate());
    }
    for (int i = 0; i < aisles_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, aisles_.get(i));
    }
    if (status_ != com.grpc.store.Store.Status.CLOSED.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(6, status_);
    }
    if (timing_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(7, getTiming());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.grpc.store.Store)) {
      return super.equals(obj);
    }
    com.grpc.store.Store other = (com.grpc.store.Store) obj;

    if (hasId() != other.hasId()) return false;
    if (hasId()) {
      if (!getId()
          .equals(other.getId())) return false;
    }
    if (!getAddress()
        .equals(other.getAddress())) return false;
    if (getContact()
        != other.getContact()) return false;
    if (hasOpeningDate() != other.hasOpeningDate()) return false;
    if (hasOpeningDate()) {
      if (!getOpeningDate()
          .equals(other.getOpeningDate())) return false;
    }
    if (!getAislesList()
        .equals(other.getAislesList())) return false;
    if (status_ != other.status_) return false;
    if (hasTiming() != other.hasTiming()) return false;
    if (hasTiming()) {
      if (!getTiming()
          .equals(other.getTiming())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasId()) {
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId().hashCode();
    }
    hash = (37 * hash) + ADDRESS_FIELD_NUMBER;
    hash = (53 * hash) + getAddress().hashCode();
    hash = (37 * hash) + CONTACT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getContact());
    if (hasOpeningDate()) {
      hash = (37 * hash) + OPENINGDATE_FIELD_NUMBER;
      hash = (53 * hash) + getOpeningDate().hashCode();
    }
    if (getAislesCount() > 0) {
      hash = (37 * hash) + AISLES_FIELD_NUMBER;
      hash = (53 * hash) + getAislesList().hashCode();
    }
    hash = (37 * hash) + STATUS_FIELD_NUMBER;
    hash = (53 * hash) + status_;
    if (hasTiming()) {
      hash = (37 * hash) + TIMING_FIELD_NUMBER;
      hash = (53 * hash) + getTiming().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.grpc.store.Store parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.grpc.store.Store parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.grpc.store.Store parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.grpc.store.Store parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.grpc.store.Store parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.grpc.store.Store parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.grpc.store.Store parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.grpc.store.Store parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.grpc.store.Store parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.grpc.store.Store parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.grpc.store.Store parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.grpc.store.Store parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.grpc.store.Store prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.grpc.store.Store}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.grpc.store.Store)
      com.grpc.store.StoreOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.grpc.store.StoreCover.internal_static_com_grpc_store_Store_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.grpc.store.StoreCover.internal_static_com_grpc_store_Store_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.grpc.store.Store.class, com.grpc.store.Store.Builder.class);
    }

    // Construct using com.grpc.store.Store.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getAislesFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (idBuilder_ == null) {
        id_ = null;
      } else {
        id_ = null;
        idBuilder_ = null;
      }
      address_ = "";

      contact_ = 0L;

      if (openingDateBuilder_ == null) {
        openingDate_ = null;
      } else {
        openingDate_ = null;
        openingDateBuilder_ = null;
      }
      if (aislesBuilder_ == null) {
        aisles_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        aislesBuilder_.clear();
      }
      status_ = 0;

      if (timingBuilder_ == null) {
        timing_ = null;
      } else {
        timing_ = null;
        timingBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.grpc.store.StoreCover.internal_static_com_grpc_store_Store_descriptor;
    }

    @java.lang.Override
    public com.grpc.store.Store getDefaultInstanceForType() {
      return com.grpc.store.Store.getDefaultInstance();
    }

    @java.lang.Override
    public com.grpc.store.Store build() {
      com.grpc.store.Store result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.grpc.store.Store buildPartial() {
      com.grpc.store.Store result = new com.grpc.store.Store(this);
      int from_bitField0_ = bitField0_;
      if (idBuilder_ == null) {
        result.id_ = id_;
      } else {
        result.id_ = idBuilder_.build();
      }
      result.address_ = address_;
      result.contact_ = contact_;
      if (openingDateBuilder_ == null) {
        result.openingDate_ = openingDate_;
      } else {
        result.openingDate_ = openingDateBuilder_.build();
      }
      if (aislesBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          aisles_ = java.util.Collections.unmodifiableList(aisles_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.aisles_ = aisles_;
      } else {
        result.aisles_ = aislesBuilder_.build();
      }
      result.status_ = status_;
      if (timingBuilder_ == null) {
        result.timing_ = timing_;
      } else {
        result.timing_ = timingBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.grpc.store.Store) {
        return mergeFrom((com.grpc.store.Store)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.grpc.store.Store other) {
      if (other == com.grpc.store.Store.getDefaultInstance()) return this;
      if (other.hasId()) {
        mergeId(other.getId());
      }
      if (!other.getAddress().isEmpty()) {
        address_ = other.address_;
        onChanged();
      }
      if (other.getContact() != 0L) {
        setContact(other.getContact());
      }
      if (other.hasOpeningDate()) {
        mergeOpeningDate(other.getOpeningDate());
      }
      if (aislesBuilder_ == null) {
        if (!other.aisles_.isEmpty()) {
          if (aisles_.isEmpty()) {
            aisles_ = other.aisles_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureAislesIsMutable();
            aisles_.addAll(other.aisles_);
          }
          onChanged();
        }
      } else {
        if (!other.aisles_.isEmpty()) {
          if (aislesBuilder_.isEmpty()) {
            aislesBuilder_.dispose();
            aislesBuilder_ = null;
            aisles_ = other.aisles_;
            bitField0_ = (bitField0_ & ~0x00000001);
            aislesBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getAislesFieldBuilder() : null;
          } else {
            aislesBuilder_.addAllMessages(other.aisles_);
          }
        }
      }
      if (other.status_ != 0) {
        setStatusValue(other.getStatusValue());
      }
      if (other.hasTiming()) {
        mergeTiming(other.getTiming());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.grpc.store.Store parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.grpc.store.Store) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private com.grpc.store.UUID id_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.grpc.store.UUID, com.grpc.store.UUID.Builder, com.grpc.store.UUIDOrBuilder> idBuilder_;
    /**
     * <code>.com.grpc.store.UUID id = 1;</code>
     * @return Whether the id field is set.
     */
    public boolean hasId() {
      return idBuilder_ != null || id_ != null;
    }
    /**
     * <code>.com.grpc.store.UUID id = 1;</code>
     * @return The id.
     */
    public com.grpc.store.UUID getId() {
      if (idBuilder_ == null) {
        return id_ == null ? com.grpc.store.UUID.getDefaultInstance() : id_;
      } else {
        return idBuilder_.getMessage();
      }
    }
    /**
     * <code>.com.grpc.store.UUID id = 1;</code>
     */
    public Builder setId(com.grpc.store.UUID value) {
      if (idBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        id_ = value;
        onChanged();
      } else {
        idBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.com.grpc.store.UUID id = 1;</code>
     */
    public Builder setId(
        com.grpc.store.UUID.Builder builderForValue) {
      if (idBuilder_ == null) {
        id_ = builderForValue.build();
        onChanged();
      } else {
        idBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.com.grpc.store.UUID id = 1;</code>
     */
    public Builder mergeId(com.grpc.store.UUID value) {
      if (idBuilder_ == null) {
        if (id_ != null) {
          id_ =
            com.grpc.store.UUID.newBuilder(id_).mergeFrom(value).buildPartial();
        } else {
          id_ = value;
        }
        onChanged();
      } else {
        idBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.com.grpc.store.UUID id = 1;</code>
     */
    public Builder clearId() {
      if (idBuilder_ == null) {
        id_ = null;
        onChanged();
      } else {
        id_ = null;
        idBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.com.grpc.store.UUID id = 1;</code>
     */
    public com.grpc.store.UUID.Builder getIdBuilder() {
      
      onChanged();
      return getIdFieldBuilder().getBuilder();
    }
    /**
     * <code>.com.grpc.store.UUID id = 1;</code>
     */
    public com.grpc.store.UUIDOrBuilder getIdOrBuilder() {
      if (idBuilder_ != null) {
        return idBuilder_.getMessageOrBuilder();
      } else {
        return id_ == null ?
            com.grpc.store.UUID.getDefaultInstance() : id_;
      }
    }
    /**
     * <code>.com.grpc.store.UUID id = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.grpc.store.UUID, com.grpc.store.UUID.Builder, com.grpc.store.UUIDOrBuilder> 
        getIdFieldBuilder() {
      if (idBuilder_ == null) {
        idBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.grpc.store.UUID, com.grpc.store.UUID.Builder, com.grpc.store.UUIDOrBuilder>(
                getId(),
                getParentForChildren(),
                isClean());
        id_ = null;
      }
      return idBuilder_;
    }

    private java.lang.Object address_ = "";
    /**
     * <code>string address = 2;</code>
     * @return The address.
     */
    public java.lang.String getAddress() {
      java.lang.Object ref = address_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        address_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string address = 2;</code>
     * @return The bytes for address.
     */
    public com.google.protobuf.ByteString
        getAddressBytes() {
      java.lang.Object ref = address_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        address_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string address = 2;</code>
     * @param value The address to set.
     * @return This builder for chaining.
     */
    public Builder setAddress(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      address_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string address = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearAddress() {
      
      address_ = getDefaultInstance().getAddress();
      onChanged();
      return this;
    }
    /**
     * <code>string address = 2;</code>
     * @param value The bytes for address to set.
     * @return This builder for chaining.
     */
    public Builder setAddressBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      address_ = value;
      onChanged();
      return this;
    }

    private long contact_ ;
    /**
     * <code>int64 contact = 3;</code>
     * @return The contact.
     */
    @java.lang.Override
    public long getContact() {
      return contact_;
    }
    /**
     * <code>int64 contact = 3;</code>
     * @param value The contact to set.
     * @return This builder for chaining.
     */
    public Builder setContact(long value) {
      
      contact_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 contact = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearContact() {
      
      contact_ = 0L;
      onChanged();
      return this;
    }

    private com.google.protobuf.Timestamp openingDate_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> openingDateBuilder_;
    /**
     * <code>.google.protobuf.Timestamp openingDate = 4;</code>
     * @return Whether the openingDate field is set.
     */
    public boolean hasOpeningDate() {
      return openingDateBuilder_ != null || openingDate_ != null;
    }
    /**
     * <code>.google.protobuf.Timestamp openingDate = 4;</code>
     * @return The openingDate.
     */
    public com.google.protobuf.Timestamp getOpeningDate() {
      if (openingDateBuilder_ == null) {
        return openingDate_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : openingDate_;
      } else {
        return openingDateBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Timestamp openingDate = 4;</code>
     */
    public Builder setOpeningDate(com.google.protobuf.Timestamp value) {
      if (openingDateBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        openingDate_ = value;
        onChanged();
      } else {
        openingDateBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp openingDate = 4;</code>
     */
    public Builder setOpeningDate(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (openingDateBuilder_ == null) {
        openingDate_ = builderForValue.build();
        onChanged();
      } else {
        openingDateBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp openingDate = 4;</code>
     */
    public Builder mergeOpeningDate(com.google.protobuf.Timestamp value) {
      if (openingDateBuilder_ == null) {
        if (openingDate_ != null) {
          openingDate_ =
            com.google.protobuf.Timestamp.newBuilder(openingDate_).mergeFrom(value).buildPartial();
        } else {
          openingDate_ = value;
        }
        onChanged();
      } else {
        openingDateBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp openingDate = 4;</code>
     */
    public Builder clearOpeningDate() {
      if (openingDateBuilder_ == null) {
        openingDate_ = null;
        onChanged();
      } else {
        openingDate_ = null;
        openingDateBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp openingDate = 4;</code>
     */
    public com.google.protobuf.Timestamp.Builder getOpeningDateBuilder() {
      
      onChanged();
      return getOpeningDateFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Timestamp openingDate = 4;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getOpeningDateOrBuilder() {
      if (openingDateBuilder_ != null) {
        return openingDateBuilder_.getMessageOrBuilder();
      } else {
        return openingDate_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : openingDate_;
      }
    }
    /**
     * <code>.google.protobuf.Timestamp openingDate = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        getOpeningDateFieldBuilder() {
      if (openingDateBuilder_ == null) {
        openingDateBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getOpeningDate(),
                getParentForChildren(),
                isClean());
        openingDate_ = null;
      }
      return openingDateBuilder_;
    }

    private java.util.List<com.grpc.store.Aisle> aisles_ =
      java.util.Collections.emptyList();
    private void ensureAislesIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        aisles_ = new java.util.ArrayList<com.grpc.store.Aisle>(aisles_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.grpc.store.Aisle, com.grpc.store.Aisle.Builder, com.grpc.store.AisleOrBuilder> aislesBuilder_;

    /**
     * <code>repeated .com.grpc.store.Aisle aisles = 5;</code>
     */
    public java.util.List<com.grpc.store.Aisle> getAislesList() {
      if (aislesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(aisles_);
      } else {
        return aislesBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .com.grpc.store.Aisle aisles = 5;</code>
     */
    public int getAislesCount() {
      if (aislesBuilder_ == null) {
        return aisles_.size();
      } else {
        return aislesBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .com.grpc.store.Aisle aisles = 5;</code>
     */
    public com.grpc.store.Aisle getAisles(int index) {
      if (aislesBuilder_ == null) {
        return aisles_.get(index);
      } else {
        return aislesBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .com.grpc.store.Aisle aisles = 5;</code>
     */
    public Builder setAisles(
        int index, com.grpc.store.Aisle value) {
      if (aislesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAislesIsMutable();
        aisles_.set(index, value);
        onChanged();
      } else {
        aislesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.grpc.store.Aisle aisles = 5;</code>
     */
    public Builder setAisles(
        int index, com.grpc.store.Aisle.Builder builderForValue) {
      if (aislesBuilder_ == null) {
        ensureAislesIsMutable();
        aisles_.set(index, builderForValue.build());
        onChanged();
      } else {
        aislesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.grpc.store.Aisle aisles = 5;</code>
     */
    public Builder addAisles(com.grpc.store.Aisle value) {
      if (aislesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAislesIsMutable();
        aisles_.add(value);
        onChanged();
      } else {
        aislesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .com.grpc.store.Aisle aisles = 5;</code>
     */
    public Builder addAisles(
        int index, com.grpc.store.Aisle value) {
      if (aislesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAislesIsMutable();
        aisles_.add(index, value);
        onChanged();
      } else {
        aislesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.grpc.store.Aisle aisles = 5;</code>
     */
    public Builder addAisles(
        com.grpc.store.Aisle.Builder builderForValue) {
      if (aislesBuilder_ == null) {
        ensureAislesIsMutable();
        aisles_.add(builderForValue.build());
        onChanged();
      } else {
        aislesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.grpc.store.Aisle aisles = 5;</code>
     */
    public Builder addAisles(
        int index, com.grpc.store.Aisle.Builder builderForValue) {
      if (aislesBuilder_ == null) {
        ensureAislesIsMutable();
        aisles_.add(index, builderForValue.build());
        onChanged();
      } else {
        aislesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.grpc.store.Aisle aisles = 5;</code>
     */
    public Builder addAllAisles(
        java.lang.Iterable<? extends com.grpc.store.Aisle> values) {
      if (aislesBuilder_ == null) {
        ensureAislesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, aisles_);
        onChanged();
      } else {
        aislesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .com.grpc.store.Aisle aisles = 5;</code>
     */
    public Builder clearAisles() {
      if (aislesBuilder_ == null) {
        aisles_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        aislesBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .com.grpc.store.Aisle aisles = 5;</code>
     */
    public Builder removeAisles(int index) {
      if (aislesBuilder_ == null) {
        ensureAislesIsMutable();
        aisles_.remove(index);
        onChanged();
      } else {
        aislesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .com.grpc.store.Aisle aisles = 5;</code>
     */
    public com.grpc.store.Aisle.Builder getAislesBuilder(
        int index) {
      return getAislesFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .com.grpc.store.Aisle aisles = 5;</code>
     */
    public com.grpc.store.AisleOrBuilder getAislesOrBuilder(
        int index) {
      if (aislesBuilder_ == null) {
        return aisles_.get(index);  } else {
        return aislesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .com.grpc.store.Aisle aisles = 5;</code>
     */
    public java.util.List<? extends com.grpc.store.AisleOrBuilder> 
         getAislesOrBuilderList() {
      if (aislesBuilder_ != null) {
        return aislesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(aisles_);
      }
    }
    /**
     * <code>repeated .com.grpc.store.Aisle aisles = 5;</code>
     */
    public com.grpc.store.Aisle.Builder addAislesBuilder() {
      return getAislesFieldBuilder().addBuilder(
          com.grpc.store.Aisle.getDefaultInstance());
    }
    /**
     * <code>repeated .com.grpc.store.Aisle aisles = 5;</code>
     */
    public com.grpc.store.Aisle.Builder addAislesBuilder(
        int index) {
      return getAislesFieldBuilder().addBuilder(
          index, com.grpc.store.Aisle.getDefaultInstance());
    }
    /**
     * <code>repeated .com.grpc.store.Aisle aisles = 5;</code>
     */
    public java.util.List<com.grpc.store.Aisle.Builder> 
         getAislesBuilderList() {
      return getAislesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.grpc.store.Aisle, com.grpc.store.Aisle.Builder, com.grpc.store.AisleOrBuilder> 
        getAislesFieldBuilder() {
      if (aislesBuilder_ == null) {
        aislesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.grpc.store.Aisle, com.grpc.store.Aisle.Builder, com.grpc.store.AisleOrBuilder>(
                aisles_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        aisles_ = null;
      }
      return aislesBuilder_;
    }

    private int status_ = 0;
    /**
     * <code>.com.grpc.store.Store.Status status = 6;</code>
     * @return The enum numeric value on the wire for status.
     */
    @java.lang.Override public int getStatusValue() {
      return status_;
    }
    /**
     * <code>.com.grpc.store.Store.Status status = 6;</code>
     * @param value The enum numeric value on the wire for status to set.
     * @return This builder for chaining.
     */
    public Builder setStatusValue(int value) {
      
      status_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.com.grpc.store.Store.Status status = 6;</code>
     * @return The status.
     */
    @java.lang.Override
    public com.grpc.store.Store.Status getStatus() {
      @SuppressWarnings("deprecation")
      com.grpc.store.Store.Status result = com.grpc.store.Store.Status.valueOf(status_);
      return result == null ? com.grpc.store.Store.Status.UNRECOGNIZED : result;
    }
    /**
     * <code>.com.grpc.store.Store.Status status = 6;</code>
     * @param value The status to set.
     * @return This builder for chaining.
     */
    public Builder setStatus(com.grpc.store.Store.Status value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      status_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.com.grpc.store.Store.Status status = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearStatus() {
      
      status_ = 0;
      onChanged();
      return this;
    }

    private com.grpc.store.Timing timing_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.grpc.store.Timing, com.grpc.store.Timing.Builder, com.grpc.store.TimingOrBuilder> timingBuilder_;
    /**
     * <code>.com.grpc.store.Timing timing = 7;</code>
     * @return Whether the timing field is set.
     */
    public boolean hasTiming() {
      return timingBuilder_ != null || timing_ != null;
    }
    /**
     * <code>.com.grpc.store.Timing timing = 7;</code>
     * @return The timing.
     */
    public com.grpc.store.Timing getTiming() {
      if (timingBuilder_ == null) {
        return timing_ == null ? com.grpc.store.Timing.getDefaultInstance() : timing_;
      } else {
        return timingBuilder_.getMessage();
      }
    }
    /**
     * <code>.com.grpc.store.Timing timing = 7;</code>
     */
    public Builder setTiming(com.grpc.store.Timing value) {
      if (timingBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        timing_ = value;
        onChanged();
      } else {
        timingBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.com.grpc.store.Timing timing = 7;</code>
     */
    public Builder setTiming(
        com.grpc.store.Timing.Builder builderForValue) {
      if (timingBuilder_ == null) {
        timing_ = builderForValue.build();
        onChanged();
      } else {
        timingBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.com.grpc.store.Timing timing = 7;</code>
     */
    public Builder mergeTiming(com.grpc.store.Timing value) {
      if (timingBuilder_ == null) {
        if (timing_ != null) {
          timing_ =
            com.grpc.store.Timing.newBuilder(timing_).mergeFrom(value).buildPartial();
        } else {
          timing_ = value;
        }
        onChanged();
      } else {
        timingBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.com.grpc.store.Timing timing = 7;</code>
     */
    public Builder clearTiming() {
      if (timingBuilder_ == null) {
        timing_ = null;
        onChanged();
      } else {
        timing_ = null;
        timingBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.com.grpc.store.Timing timing = 7;</code>
     */
    public com.grpc.store.Timing.Builder getTimingBuilder() {
      
      onChanged();
      return getTimingFieldBuilder().getBuilder();
    }
    /**
     * <code>.com.grpc.store.Timing timing = 7;</code>
     */
    public com.grpc.store.TimingOrBuilder getTimingOrBuilder() {
      if (timingBuilder_ != null) {
        return timingBuilder_.getMessageOrBuilder();
      } else {
        return timing_ == null ?
            com.grpc.store.Timing.getDefaultInstance() : timing_;
      }
    }
    /**
     * <code>.com.grpc.store.Timing timing = 7;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.grpc.store.Timing, com.grpc.store.Timing.Builder, com.grpc.store.TimingOrBuilder> 
        getTimingFieldBuilder() {
      if (timingBuilder_ == null) {
        timingBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.grpc.store.Timing, com.grpc.store.Timing.Builder, com.grpc.store.TimingOrBuilder>(
                getTiming(),
                getParentForChildren(),
                isClean());
        timing_ = null;
      }
      return timingBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.grpc.store.Store)
  }

  // @@protoc_insertion_point(class_scope:com.grpc.store.Store)
  private static final com.grpc.store.Store DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.grpc.store.Store();
  }

  public static com.grpc.store.Store getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Store>
      PARSER = new com.google.protobuf.AbstractParser<Store>() {
    @java.lang.Override
    public Store parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Store(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Store> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Store> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.grpc.store.Store getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

