// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: store.proto

package com.grpc.store;

public interface TimingOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.grpc.store.Timing)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.google.protobuf.Timestamp openAt = 1;</code>
   * @return Whether the openAt field is set.
   */
  boolean hasOpenAt();
  /**
   * <code>.google.protobuf.Timestamp openAt = 1;</code>
   * @return The openAt.
   */
  com.google.protobuf.Timestamp getOpenAt();
  /**
   * <code>.google.protobuf.Timestamp openAt = 1;</code>
   */
  com.google.protobuf.TimestampOrBuilder getOpenAtOrBuilder();

  /**
   * <code>.google.protobuf.Timestamp closeAt = 2;</code>
   * @return Whether the closeAt field is set.
   */
  boolean hasCloseAt();
  /**
   * <code>.google.protobuf.Timestamp closeAt = 2;</code>
   * @return The closeAt.
   */
  com.google.protobuf.Timestamp getCloseAt();
  /**
   * <code>.google.protobuf.Timestamp closeAt = 2;</code>
   */
  com.google.protobuf.TimestampOrBuilder getCloseAtOrBuilder();
}
